#!/bin/bash
set -euo pipefail

# DuckDB Static Build Script
# Builds DuckDB with 24 statically-linked core extensions
# Optionally adds the spatial extension for a 25-extension build
# Optionally adds robust-labs/robust RPT as an experimental extension
# Usage: ./build-duckdb-static.sh [options]
#   Options:
#     --vcpkg-dir DIR    Path to vcpkg installation (default: ~/vcpkg)
#     --duckdb-dir DIR   Path to DuckDB source (default: ~/duckdbsrc)
#     --skip-vcpkg       Skip vcpkg dependency installation
#     --clean            Clean build before starting
#     --with-spatial     Include spatial as a statically-linked extension
#     --with-robust-rpt  Include robust-labs/robust RPT as a statically-linked extension
#     --help             Show this help

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default paths
VCPKG_DIR="$HOME/vcpkg"
DUCKDB_DIR="$HOME/duckdbsrc"
SKIP_VCPKG=false
CLEAN_BUILD=false
WITH_SPATIAL=false
WITH_ROBUST_RPT=false

require_cmd() {
    local cmd="$1"
    if ! command -v "$cmd" >/dev/null 2>&1; then
        log_error "$cmd not found. Please install it first."
        exit 1
    fi
}

ensure_include_after_git_tag() {
    local file="$1"
    local include_line="$2"
    if [ ! -f "$file" ]; then
        return 0
    fi
    if grep -Fq "$include_line" "$file"; then
        return 0
    fi
    sed -i "/GIT_TAG/a\\            $include_line" "$file"
}

sanitize_dirty_fetchcontent_deps() {
    local removed_any=false
    local dep_dir dep_base dep_prefix
    shopt -s nullglob
    for dep_dir in _deps/*_extension_fc-src _deps/*_extension-src; do
        [ -d "$dep_dir/.git" ] || continue
        if [ -n "$(git -C "$dep_dir" status --porcelain 2>/dev/null || true)" ]; then
            dep_base=$(basename "$dep_dir")
            dep_prefix="${dep_base%-src}"
            log_warning "Dirty FetchContent repo detected: $dep_dir"
            log_warning "Removing cached dependency checkout to avoid git stash/update conflicts"
            rm -rf "$dep_dir" "_deps/${dep_prefix}-build" "_deps/${dep_prefix}-subbuild"
            removed_any=true
        fi
    done
    shopt -u nullglob

    if [ "$removed_any" = true ]; then
        log_success "Removed dirty FetchContent dependency checkouts"
    fi
}

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --vcpkg-dir)
      if [[ $# -lt 2 ]]; then
        echo -e "${RED}[ERROR]${NC} --vcpkg-dir requires a value"
        exit 1
      fi
      VCPKG_DIR="$2"
      shift 2
      ;;
    --duckdb-dir)
      if [[ $# -lt 2 ]]; then
        echo -e "${RED}[ERROR]${NC} --duckdb-dir requires a value"
        exit 1
      fi
      DUCKDB_DIR="$2"
      shift 2
      ;;
    --skip-vcpkg)
      SKIP_VCPKG=true
      shift
      ;;
    --clean)
      CLEAN_BUILD=true
      shift
      ;;
    --with-spatial)
      WITH_SPATIAL=true
      shift
      ;;
    --with-robust-rpt)
      WITH_ROBUST_RPT=true
      shift
      ;;
    --help)
      grep '^#' "$0" | grep -v '#!/bin/bash' | sed 's/^# //'
      exit 0
      ;;
    *)
      echo -e "${RED}Unknown option: $1${NC}"
      exit 1
      ;;
  esac
done

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check prerequisites
log_info "Checking prerequisites..."
for cmd in git cmake make gcc g++ sed awk nproc python3 cargo rustc; do
    require_cmd "$cmd"
done
if [ "$WITH_SPATIAL" = true ]; then
    require_cmd xxd
fi
log_success "All prerequisites found"

# Step 1: Install/check vcpkg
log_info "Step 1: Setting up vcpkg at $VCPKG_DIR"
if [ ! -d "$VCPKG_DIR" ]; then
    log_info "Cloning vcpkg..."
    git clone https://github.com/microsoft/vcpkg.git "$VCPKG_DIR"
    cd "$VCPKG_DIR"
    ./bootstrap-vcpkg.sh
    log_success "vcpkg installed"
else
    log_success "vcpkg already exists at $VCPKG_DIR"
fi

# Step 2: Clone/check DuckDB
log_info "Step 2: Setting up DuckDB at $DUCKDB_DIR"
if [ ! -d "$DUCKDB_DIR" ]; then
    log_info "Cloning DuckDB..."
    git clone https://github.com/duckdb/duckdb.git "$DUCKDB_DIR"
    log_success "DuckDB cloned"
else
    log_success "DuckDB already exists at $DUCKDB_DIR"
fi

cd "$DUCKDB_DIR"

# Clean build if requested
if [ "$CLEAN_BUILD" = true ]; then
    log_info "Cleaning previous build artifacts..."
    rm -rf CMakeCache.txt CMakeFiles/ build*/ _deps/ duckdb duckdb_platform_* *.log \
        cmake_install.cmake DuckDB*.cmake DuckDBExports.cmake compile_commands.json \
        codegen/include/* codegen/src/*
    log_success "Build artifacts cleaned"
fi

# Step 3: Create extension configuration
log_info "Step 3: Creating extension configuration..."
mkdir -p extension
cat > extension/extension_config_local.cmake << EOF
duckdb_extension_load(autocomplete)
duckdb_extension_load(icu)
duckdb_extension_load(tpcds)
duckdb_extension_load(tpch)
duckdb_extension_load(fts)
duckdb_extension_load(json)
duckdb_extension_load(parquet)
duckdb_extension_load(sqlite_scanner)
duckdb_extension_load(postgres_scanner APPLY_PATCHES)
duckdb_extension_load(mysql_scanner APPLY_PATCHES)
duckdb_extension_load(httpfs)
duckdb_extension_load(excel)
duckdb_extension_load(vss)
duckdb_extension_load(inet)
duckdb_extension_load(avro)
duckdb_extension_load(aws)
duckdb_extension_load(azure)
duckdb_extension_load(iceberg)
duckdb_extension_load(ducklake)
duckdb_extension_load(delta APPLY_PATCHES)
duckdb_extension_load(unity_catalog)
EOF
if [ "$WITH_SPATIAL" = true ]; then
    echo "duckdb_extension_load(spatial APPLY_PATCHES)" >> extension/extension_config_local.cmake
fi
if [ "$WITH_ROBUST_RPT" = true ]; then
    cat >> extension/extension_config_local.cmake << EOF
duckdb_extension_load(robust
    GIT_URL https://github.com/robust-labs/robust
    GIT_TAG 5ec7800e000291e27f7433cb513ba606fc675fc1
    APPLY_PATCHES
)
EOF
fi
log_success "Extension configuration created"

# Step 4: Remove DONT_LINK flags and add INCLUDE_DIRs
log_info "Step 4: Patching extension configs..."
if [ -f .github/config/extensions/fts.cmake ]; then
    sed -i '/DONT_LINK/d' .github/config/extensions/fts.cmake
    if ! grep -Fq "INCLUDE_DIR extension/fts/include" .github/config/extensions/fts.cmake; then
        sed -i '/GIT_TAG/a\        INCLUDE_DIR extension/fts/include' .github/config/extensions/fts.cmake
    fi
    log_success "FTS config patched"
fi
if [ -f .github/config/extensions/vss.cmake ]; then
    sed -i '/DONT_LINK/d' .github/config/extensions/vss.cmake
    log_success "VSS config patched"
fi
if [ -f .github/config/extensions/postgres_scanner.cmake ]; then
    sed -i '/DONT_LINK/d' .github/config/extensions/postgres_scanner.cmake
    ensure_include_after_git_tag .github/config/extensions/postgres_scanner.cmake "INCLUDE_DIR src/include"
    log_success "postgres_scanner config patched"
fi
if [ -f .github/config/extensions/mysql_scanner.cmake ]; then
    sed -i '/DONT_LINK/d' .github/config/extensions/mysql_scanner.cmake
    ensure_include_after_git_tag .github/config/extensions/mysql_scanner.cmake "INCLUDE_DIR src/include"
    log_success "mysql_scanner config patched"
fi
if [ "$WITH_SPATIAL" = true ] && [ -f .github/config/extensions/spatial.cmake ]; then
    sed -i '/DONT_LINK/d' .github/config/extensions/spatial.cmake
    log_success "spatial config patched"
fi
if [ "$WITH_ROBUST_RPT" = true ]; then
    mkdir -p .github/config/extensions
    cat > .github/config/extensions/robust.cmake << 'EOF'
duckdb_extension_load(robust
    GIT_URL https://github.com/robust-labs/robust
    GIT_TAG 5ec7800e000291e27f7433cb513ba606fc675fc1
    APPLY_PATCHES
)
EOF
    log_success "robust RPT config created"
fi

# Step 4b: Create extension patch files
log_info "Step 4b: Creating extension patch files..."

mkdir -p .github/patches/extensions/mysql_scanner
cat > .github/patches/extensions/mysql_scanner/static_build.patch << 'PATCH_EOF'
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 081124a..f0a2df6 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -12,6 +12,9 @@ include_directories(${MYSQL_INCLUDE_DIR})
 
 add_subdirectory(src)
 
+# Static extension build (added by build script)
+build_static_extension(${TARGET_NAME} "" ${ALL_OBJECT_FILES})
+
 set(PARAMETERS "-no-warnings")
 build_loadable_extension(${TARGET_NAME} ${PARAMETERS} ${ALL_OBJECT_FILES})
 
@@ -19,3 +22,8 @@ build_loadable_extension(${TARGET_NAME} ${PARAMETERS} ${ALL_OBJECT_FILES})
 target_include_directories(${TARGET_NAME}_loadable_extension
                            PRIVATE include ${MYSQL_INCLUDE_DIR})
 target_link_libraries(${TARGET_NAME}_loadable_extension ${MYSQL_LIBRARIES})
+
+# Static binary includes/libs (added by build script)
+target_include_directories(${TARGET_NAME}_extension
+                           PRIVATE include src/include ${MYSQL_INCLUDE_DIR})
+target_link_libraries(${TARGET_NAME}_extension ${MYSQL_LIBRARIES})
PATCH_EOF

mkdir -p .github/patches/extensions/postgres_scanner
cat > .github/patches/extensions/postgres_scanner/static_build.patch << 'PATCH_EOF'
diff --git a/CMakeLists.txt b/CMakeLists.txt
index d0e5371..e7478aa 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -185,6 +185,10 @@ if(NOT EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/postgres)
   message(STATUS "Finished setting up PostgreSQL source code!")
 endif()
 
+# Static extension build (added by build script)
+build_static_extension(${TARGET_NAME} "" ${ALL_OBJECT_FILES}
+                       ${LIBPG_SOURCES_FULLPATH})
+
 set(PARAMETERS "-no-warnings")
 build_loadable_extension(${TARGET_NAME} ${PARAMETERS} ${ALL_OBJECT_FILES}
                          ${LIBPG_SOURCES_FULLPATH})
@@ -208,3 +212,11 @@ if(WIN32)
   target_link_libraries(${TARGET_NAME}_loadable_extension wsock32 ws2_32
                         wldap32 secur32 crypt32)
 endif()
+
+# Static binary includes/libs (added by build script)
+target_include_directories(
+  ${TARGET_NAME}_extension
+  PRIVATE include src/include postgres/src/include postgres/src/backend
+          postgres/src/interfaces/libpq ${OPENSSL_INCLUDE_DIR})
+target_link_libraries(${TARGET_NAME}_extension ${OPENSSL_LIBRARIES})
+set_property(TARGET ${TARGET_NAME}_extension PROPERTY C_STANDARD 99)
PATCH_EOF

mkdir -p .github/patches/extensions/delta
cat > .github/patches/extensions/delta/rustls.patch << 'PATCH_EOF'
diff --git a/CMakeLists.txt b/CMakeLists.txt
index ff33ba9..f2e3361 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -162,13 +162,9 @@ ExternalProject_Add(
   # Build debug build
   BUILD_COMMAND
     ${CMAKE_COMMAND} -E env ${RUST_UNSET_ENV_VARS} ${RUST_ENV_VARS} cargo build
-    --package delta_kernel_ffi --workspace --profile=${CARGO_PROFILE} --all-features
+    --package delta_kernel_ffi --profile=${CARGO_PROFILE} --no-default-features --features "default-engine-rustls,tracing,test-ffi"
     ${RUST_PLATFORM_PARAM}
-  # Build DATs
-  COMMAND
-    ${CMAKE_COMMAND} -E env ${RUST_UNSET_ENV_VARS} ${RUST_ENV_VARS} cargo build
-    --manifest-path=${CMAKE_BINARY_DIR}/rust/src/delta_kernel/acceptance/Cargo.toml
   # Define the byproducts, required for building with Ninja
   BUILD_BYPRODUCTS "${DELTA_KERNEL_LIBPATH}"
   BUILD_BYPRODUCTS "${DELTA_KERNEL_FFI_HEADER_C}"
   BUILD_BYPRODUCTS "${DELTA_KERNEL_FFI_HEADER_CXX}"
PATCH_EOF

if [ "$WITH_ROBUST_RPT" = true ]; then
    mkdir -p .github/patches/extensions/robust
    base64 -d > .github/patches/extensions/robust/current-duckdb-compat.patch << 'PATCH_B64'
ZGlmZiAtLWdpdCBhL3NyYy9pbmNsdWRlL3Byb2JlX2VtcHR5X3JlZ2lzdHJ5LmhwcCBiL3NyYy9p
bmNsdWRlL3Byb2JlX2VtcHR5X3JlZ2lzdHJ5LmhwcApuZXcgZmlsZSBtb2RlIDEwMDY0NAppbmRl
eCAwMDAwMDAwLi4xYjMzOTZmCi0tLSAvZGV2L251bGwKKysrIGIvc3JjL2luY2x1ZGUvcHJvYmVf
ZW1wdHlfcmVnaXN0cnkuaHBwCkBAIC0wLDAgKzEsNDEgQEAKKyNwcmFnbWEgb25jZQorCisjaW5j
bHVkZSAiZHVja2RiL21haW4vY2xpZW50X2NvbnRleHQuaHBwIgorI2luY2x1ZGUgImR1Y2tkYi9t
YWluL2NsaWVudF9jb250ZXh0X3N0YXRlLmhwcCIKKyNpbmNsdWRlICJkdWNrZGIvY29tbW9uL3No
YXJlZF9wdHIuaHBwIgorI2luY2x1ZGUgImR1Y2tkYi9jb21tb24vY29tbW9uLmhwcCIKKyNpbmNs
dWRlIDxhdG9taWM+CisjaW5jbHVkZSA8bXV0ZXg+CisjaW5jbHVkZSA8dW5vcmRlcmVkX21hcD4K
KworbmFtZXNwYWNlIGR1Y2tkYiB7CisKK2NsYXNzIFByb2JlRW1wdHlSZWdpc3RyeSA6IHB1Ymxp
YyBDbGllbnRDb250ZXh0U3RhdGUgeworcHVibGljOgorCXNoYXJlZF9wdHI8c3RkOjphdG9taWM8
Ym9vbD4+IEdldE9yQ3JlYXRlKGlkeF90IHRhYmxlX2lkeCkgeworCQlsb2NrX2d1YXJkPG11dGV4
PiBndWFyZChyZWdpc3RyeV9sb2NrKTsKKwkJYXV0byBpdCA9IGZsYWdzLmZpbmQodGFibGVfaWR4
KTsKKwkJaWYgKGl0ICE9IGZsYWdzLmVuZCgpKSB7CisJCQlyZXR1cm4gaXQtPnNlY29uZDsKKwkJ
fQorCQlhdXRvIGZsYWcgPSBtYWtlX3NoYXJlZF9wdHI8c3RkOjphdG9taWM8Ym9vbD4+KGZhbHNl
KTsKKwkJZmxhZ3MuZW1wbGFjZSh0YWJsZV9pZHgsIGZsYWcpOworCQlyZXR1cm4gZmxhZzsKKwl9
CisKK3ByaXZhdGU6CisJbXV0ZXggcmVnaXN0cnlfbG9jazsKKwl1bm9yZGVyZWRfbWFwPGlkeF90
LCBzaGFyZWRfcHRyPHN0ZDo6YXRvbWljPGJvb2w+Pj4gZmxhZ3M7Cit9OworCitzdGF0aWMgaW5s
aW5lIHNoYXJlZF9wdHI8UHJvYmVFbXB0eVJlZ2lzdHJ5PiBHZXRQcm9iZUVtcHR5UmVnaXN0cnko
Q2xpZW50Q29udGV4dCAmY29udGV4dCkgeworCWF1dG8gc3RhdGUgPSBjb250ZXh0LnJlZ2lzdGVy
ZWRfc3RhdGUtPkdldDxQcm9iZUVtcHR5UmVnaXN0cnk+KCJyb2J1c3RfcHJvYmVfZW1wdHlfcmVn
aXN0cnkiKTsKKwlpZiAoc3RhdGUpIHsKKwkJcmV0dXJuIHN0YXRlOworCX0KKwlhdXRvIHJlZ2lz
dHJ5ID0gbWFrZV9zaGFyZWRfcHRyPFByb2JlRW1wdHlSZWdpc3RyeT4oKTsKKwljb250ZXh0LnJl
Z2lzdGVyZWRfc3RhdGUtPkluc2VydCgicm9idXN0X3Byb2JlX2VtcHR5X3JlZ2lzdHJ5IiwgcmVn
aXN0cnkpOworCXJldHVybiByZWdpc3RyeTsKK30KKworfSAvLyBuYW1lc3BhY2UgZHVja2RiCmRp
ZmYgLS1naXQgYS9zcmMvaW5jbHVkZS9yb2J1c3RfcHJvZmlsaW5nLmhwcCBiL3NyYy9pbmNsdWRl
L3JvYnVzdF9wcm9maWxpbmcuaHBwCmluZGV4IDFlNmFiZjQuLmJlZTM2MzIgMTAwNjQ0Ci0tLSBh
L3NyYy9pbmNsdWRlL3JvYnVzdF9wcm9maWxpbmcuaHBwCisrKyBiL3NyYy9pbmNsdWRlL3JvYnVz
dF9wcm9maWxpbmcuaHBwCkBAIC04MSwxNyArODEsMTcgQEAgcHVibGljOgogCQlzdGF0cy0+aXNf
Zm9yd2FyZF9wYXNzID0gaXNfZm9yd2FyZF9wYXNzOwogCQkvLyBleHRyYWN0IHVuaXF1ZSBwcm9i
ZSB0YWJsZSBpbmRpY2VzIGZyb20gcHJvYmUgY29sdW1ucwogCQlmb3IgKGNvbnN0IGF1dG8gJmNv
bCA6IHByb2JlX2NvbHVtbnMpIHsKLQkJCWlmIChzdGF0cy0+cHJvYmVfdGFibGVfaW5kaWNlcy5l
bXB0eSgpIHx8IHN0YXRzLT5wcm9iZV90YWJsZV9pbmRpY2VzLmJhY2soKSAhPSBjb2wudGFibGVf
aW5kZXgpIHsKKwkJCWlmIChzdGF0cy0+cHJvYmVfdGFibGVfaW5kaWNlcy5lbXB0eSgpIHx8IHN0
YXRzLT5wcm9iZV90YWJsZV9pbmRpY2VzLmJhY2soKSAhPSBjb2wudGFibGVfaW5kZXguaW5kZXgp
IHsKIAkJCQkvLyBjaGVjayBpZiBhbHJlYWR5IHByZXNlbnQKIAkJCQlib29sIGZvdW5kID0gZmFs
c2U7CiAJCQkJZm9yIChhdXRvIGlkeCA6IHN0YXRzLT5wcm9iZV90YWJsZV9pbmRpY2VzKSB7Ci0J
CQkJCWlmIChpZHggPT0gY29sLnRhYmxlX2luZGV4KSB7CisJCQkJCWlmIChpZHggPT0gY29sLnRh
YmxlX2luZGV4LmluZGV4KSB7CiAJCQkJCQlmb3VuZCA9IHRydWU7CiAJCQkJCQlicmVhazsKIAkJ
CQkJfQogCQkJCX0KIAkJCQlpZiAoIWZvdW5kKSB7Ci0JCQkJCXN0YXRzLT5wcm9iZV90YWJsZV9p
bmRpY2VzLnB1c2hfYmFjayhjb2wudGFibGVfaW5kZXgpOworCQkJCQlzdGF0cy0+cHJvYmVfdGFi
bGVfaW5kaWNlcy5wdXNoX2JhY2soY29sLnRhYmxlX2luZGV4LmluZGV4KTsKIAkJCQl9CiAJCQl9
CiAJCX0KZGlmZiAtLWdpdCBhL3NyYy9vcGVyYXRvcnMvbG9naWNhbF9jcmVhdGVfZmlsdGVyLmNw
cCBiL3NyYy9vcGVyYXRvcnMvbG9naWNhbF9jcmVhdGVfZmlsdGVyLmNwcAppbmRleCBmNjJjOTU3
Li41ODY4NTZjIDEwMDY0NAotLS0gYS9zcmMvb3BlcmF0b3JzL2xvZ2ljYWxfY3JlYXRlX2ZpbHRl
ci5jcHAKKysrIGIvc3JjL29wZXJhdG9ycy9sb2dpY2FsX2NyZWF0ZV9maWx0ZXIuY3BwCkBAIC0y
OSw3ICsyOSw3IEBAIEluc2VydGlvbk9yZGVyUHJlc2VydmluZ01hcDxzdHJpbmc+IExvZ2ljYWxD
cmVhdGVGaWx0ZXI6OlBhcmFtc1RvU3RyaW5nKCkgY29uc3QKIAlmb3IgKGNvbnN0IGF1dG8gJmNv
bCA6IGZpbHRlcl9vcGVyYXRpb24ucHJvYmVfY29sdW1ucykgewogCQlib29sIGZvdW5kID0gZmFs
c2U7CiAJCWZvciAoYXV0byBpZHggOiBzZWVuX3Byb2JlKSB7Ci0JCQlpZiAoaWR4ID09IGNvbC50
YWJsZV9pbmRleCkgeworCQkJaWYgKGlkeCA9PSBjb2wudGFibGVfaW5kZXguaW5kZXgpIHsKIAkJ
CQlmb3VuZCA9IHRydWU7CiAJCQkJYnJlYWs7CiAJCQl9CkBAIC0zNyw4ICszNyw4IEBAIEluc2Vy
dGlvbk9yZGVyUHJlc2VydmluZ01hcDxzdHJpbmc+IExvZ2ljYWxDcmVhdGVGaWx0ZXI6OlBhcmFt
c1RvU3RyaW5nKCkgY29uc3QKIAkJaWYgKCFmb3VuZCkgewogCQkJaWYgKCFwcm9iZV90YWJsZXMu
ZW1wdHkoKSkKIAkJCQlwcm9iZV90YWJsZXMgKz0gIiwgIjsKLQkJCXByb2JlX3RhYmxlcyArPSB0
b19zdHJpbmcoY29sLnRhYmxlX2luZGV4KTsKLQkJCXNlZW5fcHJvYmUucHVzaF9iYWNrKGNvbC50
YWJsZV9pbmRleCk7CisJCQlwcm9iZV90YWJsZXMgKz0gdG9fc3RyaW5nKGNvbC50YWJsZV9pbmRl
eC5pbmRleCk7CisJCQlzZWVuX3Byb2JlLnB1c2hfYmFjayhjb2wudGFibGVfaW5kZXguaW5kZXgp
OwogCQl9CiAJfQogCXJlc3VsdFsiUHJvYmUgVGFibGVzIl0gPSBwcm9iZV90YWJsZXM7CkBAIC00
OCw3ICs0OCw3IEBAIEluc2VydGlvbk9yZGVyUHJlc2VydmluZ01hcDxzdHJpbmc+IExvZ2ljYWxD
cmVhdGVGaWx0ZXI6OlBhcmFtc1RvU3RyaW5nKCkgY29uc3QKIAkJaWYgKGkgPiAwKSB7CiAJCQli
dWlsZF9jb2xzICs9ICIsICI7CiAJCX0KLQkJYnVpbGRfY29scyArPSAiKCIgKyB0b19zdHJpbmco
ZmlsdGVyX29wZXJhdGlvbi5idWlsZF9jb2x1bW5zW2ldLnRhYmxlX2luZGV4KSArICIuIiArCisJ
CWJ1aWxkX2NvbHMgKz0gIigiICsgdG9fc3RyaW5nKGZpbHRlcl9vcGVyYXRpb24uYnVpbGRfY29s
dW1uc1tpXS50YWJsZV9pbmRleC5pbmRleCkgKyAiLiIgKwogCQkgICAgICAgICAgICAgIHRvX3N0
cmluZyhmaWx0ZXJfb3BlcmF0aW9uLmJ1aWxkX2NvbHVtbnNbaV0uY29sdW1uX2luZGV4KSArICIp
IjsKIAl9CiAJcmVzdWx0WyJCdWlsZCBDb2x1bW5zIl0gPSBidWlsZF9jb2xzOwpkaWZmIC0tZ2l0
IGEvc3JjL29wZXJhdG9ycy9sb2dpY2FsX2NyZWF0ZV9maWx0ZXIuaHBwIGIvc3JjL29wZXJhdG9y
cy9sb2dpY2FsX2NyZWF0ZV9maWx0ZXIuaHBwCmluZGV4IGMyNGQ4NzcuLjQwY2UwOTkgMTAwNjQ0
Ci0tLSBhL3NyYy9vcGVyYXRvcnMvbG9naWNhbF9jcmVhdGVfZmlsdGVyLmhwcAorKysgYi9zcmMv
b3BlcmF0b3JzL2xvZ2ljYWxfY3JlYXRlX2ZpbHRlci5ocHAKQEAgLTEwLDYgKzEwLDcgQEAKICNp
bmNsdWRlICJkdWNrZGIvcGxhbm5lci9sb2dpY2FsX29wZXJhdG9yLmhwcCIKICNpbmNsdWRlICJk
dWNrZGIvcGxhbm5lci9vcGVyYXRvci9sb2dpY2FsX2V4dGVuc2lvbl9vcGVyYXRvci5ocHAiCiAj
aW5jbHVkZSAiZHVja2RiL3BsYW5uZXIvdGFibGVfZmlsdGVyLmhwcCIKKyNpbmNsdWRlICJkdWNr
ZGIvcGxhbm5lci90YWJsZV9maWx0ZXJfc2V0LmhwcCIKICNpbmNsdWRlICIuLi9vcHRpbWl6ZXIv
Z3JhcGhfbWFuYWdlci5ocHAiCiAKIG5hbWVzcGFjZSBkdWNrZGIgewpkaWZmIC0tZ2l0IGEvc3Jj
L29wZXJhdG9ycy9sb2dpY2FsX3Byb2JlX2ZpbHRlci5jcHAgYi9zcmMvb3BlcmF0b3JzL2xvZ2lj
YWxfcHJvYmVfZmlsdGVyLmNwcAppbmRleCAzMjkzMjAzLi44MzBhZWIyIDEwMDY0NAotLS0gYS9z
cmMvb3BlcmF0b3JzL2xvZ2ljYWxfcHJvYmVfZmlsdGVyLmNwcAorKysgYi9zcmMvb3BlcmF0b3Jz
L2xvZ2ljYWxfcHJvYmVfZmlsdGVyLmNwcApAQCAtMjQsNyArMjQsNyBAQCBJbnNlcnRpb25PcmRl
clByZXNlcnZpbmdNYXA8c3RyaW5nPiBMb2dpY2FsUHJvYmVGaWx0ZXI6OlBhcmFtc1RvU3RyaW5n
KCkgY29uc3QgewogCQlpZiAoaSA+IDApIHsKIAkJCXByb2JlX2NvbHMgKz0gIiwgIjsKIAkJfQot
CQlwcm9iZV9jb2xzICs9ICIoIiArIHRvX3N0cmluZyhmaWx0ZXJfb3BlcmF0aW9uLnByb2JlX2Nv
bHVtbnNbaV0udGFibGVfaW5kZXgpICsgIi4iICsKKwkJcHJvYmVfY29scyArPSAiKCIgKyB0b19z
dHJpbmcoZmlsdGVyX29wZXJhdGlvbi5wcm9iZV9jb2x1bW5zW2ldLnRhYmxlX2luZGV4LmluZGV4
KSArICIuIiArCiAJCSAgICAgICAgICAgICAgdG9fc3RyaW5nKGZpbHRlcl9vcGVyYXRpb24ucHJv
YmVfY29sdW1uc1tpXS5jb2x1bW5faW5kZXgpICsgIikiOwogCX0KIAlyZXN1bHRbIlByb2JlIENv
bHVtbnMiXSA9IHByb2JlX2NvbHM7CkBAIC02MSwxNCArNjEsMTQgQEAgUGh5c2ljYWxPcGVyYXRv
ciAmTG9naWNhbFByb2JlRmlsdGVyOjpDcmVhdGVQbGFuKENsaWVudENvbnRleHQgJmNvbnRleHQs
IFBoeXNpY2EKIAkJUHJpbnRlcjo6UHJpbnQoU3RyaW5nVXRpbDo6Rm9ybWF0KCJbUkVTT0xWRV0g
Y2hpbGRfYmluZGluZ3Muc2l6ZSgpPSV6dSIsIGNoaWxkX2JpbmRpbmdzLnNpemUoKSkpOwogCQlm
b3IgKGlkeF90IGogPSAwOyBqIDwgY2hpbGRfYmluZGluZ3Muc2l6ZSgpOyBqKyspIHsKIAkJCVBy
aW50ZXI6OlByaW50KFN0cmluZ1V0aWw6OkZvcm1hdCgiICBjaGlsZF9iaW5kaW5nc1slbGx1XSA9
IHRhYmxlX2lkeD0lbGx1LCBjb2xfaWR4PSVsbHUiLAotCQkJICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICh1bnNpZ25lZCBsb25nIGxvbmcpaiwgKHVuc2lnbmVkIGxvbmcgbG9uZylj
aGlsZF9iaW5kaW5nc1tqXS50YWJsZV9pbmRleCwKKwkJCSAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAodW5zaWduZWQgbG9uZyBsb25nKWosICh1bnNpZ25lZCBsb25nIGxvbmcpY2hp
bGRfYmluZGluZ3Nbal0udGFibGVfaW5kZXguaW5kZXgsCiAJCQkgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgKHVuc2lnbmVkIGxvbmcgbG9uZyljaGlsZF9iaW5kaW5nc1tqXS5jb2x1
bW5faW5kZXgpKTsKIAkJfQogI2VuZGlmCiAKIAkJZm9yIChjb25zdCBDb2x1bW5CaW5kaW5nICZj
b2x1bW5fYmluZGluZyA6IGZpbHRlcl9vcGVyYXRpb24ucHJvYmVfY29sdW1ucykgewogCQkJRF9Q
UklOVEYoIltSRVNPTFZFXSBMb29raW5nIGZvciBwcm9iZV9jb2x1bW46IHRhYmxlX2lkeD0lbGx1
LCBjb2xfaWR4PSVsbHUiLAotCQkJICAgICAgICAgKHVuc2lnbmVkIGxvbmcgbG9uZyljb2x1bW5f
YmluZGluZy50YWJsZV9pbmRleCwgKHVuc2lnbmVkIGxvbmcgbG9uZyljb2x1bW5fYmluZGluZy5j
b2x1bW5faW5kZXgpOworCQkJICAgICAgICAgKHVuc2lnbmVkIGxvbmcgbG9uZyljb2x1bW5fYmlu
ZGluZy50YWJsZV9pbmRleC5pbmRleCwgKHVuc2lnbmVkIGxvbmcgbG9uZyljb2x1bW5fYmluZGlu
Zy5jb2x1bW5faW5kZXgpOwogCQkJLy8gZmluZCB0aGUgcG9zaXRpb24gb2YgdGhlIGZpbHRlciBj
b2x1bW4gQ29sdW1uQmluZGluZyBpbiB0aGUgY2h1bmsgY29sdW1ucwogCQkJZm9yIChpZHhfdCBp
ID0gMDsgaSA8IGNoaWxkX2JpbmRpbmdzLnNpemUoKTsgaSsrKSB7CiAJCQkJaWYgKGNoaWxkX2Jp
bmRpbmdzW2ldLnRhYmxlX2luZGV4ID09IGNvbHVtbl9iaW5kaW5nLnRhYmxlX2luZGV4ICYmCmRp
ZmYgLS1naXQgYS9zcmMvb3BlcmF0b3JzL3BoeXNpY2FsX2NyZWF0ZV9maWx0ZXIuY3BwIGIvc3Jj
L29wZXJhdG9ycy9waHlzaWNhbF9jcmVhdGVfZmlsdGVyLmNwcAppbmRleCA0MTM0MjExLi40NjIy
ODRlIDEwMDY0NAotLS0gYS9zcmMvb3BlcmF0b3JzL3BoeXNpY2FsX2NyZWF0ZV9maWx0ZXIuY3Bw
CisrKyBiL3NyYy9vcGVyYXRvcnMvcGh5c2ljYWxfY3JlYXRlX2ZpbHRlci5jcHAKQEAgLTQ4LDcg
KzQ4LDcgQEAgSW5zZXJ0aW9uT3JkZXJQcmVzZXJ2aW5nTWFwPHN0cmluZz4gUGh5c2ljYWxDcmVh
dGVGaWx0ZXI6OlBhcmFtc1RvU3RyaW5nKCkgY29uc3QKIAlmb3IgKGNvbnN0IGF1dG8gJmNvbCA6
IGZpbHRlcl9vcGVyYXRpb24tPnByb2JlX2NvbHVtbnMpIHsKIAkJYm9vbCBmb3VuZCA9IGZhbHNl
OwogCQlmb3IgKGF1dG8gaWR4IDogc2Vlbl9wcm9iZSkgewotCQkJaWYgKGlkeCA9PSBjb2wudGFi
bGVfaW5kZXgpIHsKKwkJCWlmIChpZHggPT0gY29sLnRhYmxlX2luZGV4LmluZGV4KSB7CiAJCQkJ
Zm91bmQgPSB0cnVlOwogCQkJCWJyZWFrOwogCQkJfQpAQCAtNTYsOCArNTYsOCBAQCBJbnNlcnRp
b25PcmRlclByZXNlcnZpbmdNYXA8c3RyaW5nPiBQaHlzaWNhbENyZWF0ZUZpbHRlcjo6UGFyYW1z
VG9TdHJpbmcoKSBjb25zdAogCQlpZiAoIWZvdW5kKSB7CiAJCQlpZiAoIXByb2JlX3RhYmxlcy5l
bXB0eSgpKQogCQkJCXByb2JlX3RhYmxlcyArPSAiLCAiOwotCQkJcHJvYmVfdGFibGVzICs9IHRv
X3N0cmluZyhjb2wudGFibGVfaW5kZXgpOwotCQkJc2Vlbl9wcm9iZS5wdXNoX2JhY2soY29sLnRh
YmxlX2luZGV4KTsKKwkJCXByb2JlX3RhYmxlcyArPSB0b19zdHJpbmcoY29sLnRhYmxlX2luZGV4
LmluZGV4KTsKKwkJCXNlZW5fcHJvYmUucHVzaF9iYWNrKGNvbC50YWJsZV9pbmRleC5pbmRleCk7
CiAJCX0KIAl9CiAJcmVzdWx0WyJQcm9iZSBUYWJsZXMiXSA9IHByb2JlX3RhYmxlczsKQEAgLTY3
LDcgKzY3LDcgQEAgSW5zZXJ0aW9uT3JkZXJQcmVzZXJ2aW5nTWFwPHN0cmluZz4gUGh5c2ljYWxD
cmVhdGVGaWx0ZXI6OlBhcmFtc1RvU3RyaW5nKCkgY29uc3QKIAkJaWYgKGkgPiAwKSB7CiAJCQli
dWlsZF9jb2xzICs9ICIsICI7CiAJCX0KLQkJYnVpbGRfY29scyArPSAiKCIgKyB0b19zdHJpbmco
ZmlsdGVyX29wZXJhdGlvbi0+YnVpbGRfY29sdW1uc1tpXS50YWJsZV9pbmRleCkgKyAiLiIgKwor
CQlidWlsZF9jb2xzICs9ICIoIiArIHRvX3N0cmluZyhmaWx0ZXJfb3BlcmF0aW9uLT5idWlsZF9j
b2x1bW5zW2ldLnRhYmxlX2luZGV4LmluZGV4KSArICIuIiArCiAJCSAgICAgICAgICAgICAgdG9f
c3RyaW5nKGZpbHRlcl9vcGVyYXRpb24tPmJ1aWxkX2NvbHVtbnNbaV0uY29sdW1uX2luZGV4KSAr
ICIpIjsKIAl9CiAJcmVzdWx0WyJCdWlsZCBDb2x1bW5zIl0gPSBidWlsZF9jb2xzOwpAQCAtMzY3
LDcgKzM2Nyw3IEBAIHN0YXRpYyB2b2lkIFB1c2hEeW5hbWljRmlsdGVycyhjb25zdCBQaHlzaWNh
bENyZWF0ZUZpbHRlciAmb3AsIGNvbnN0IENyZWF0ZUZpbHRlCiAJCWZvciAoYXV0byAmdGFyZ2V0
IDogb3AucHVzaGRvd25fdGFyZ2V0cykgewogCQkJYXV0byBhbHdheXNfZmFsc2UgPQogCQkJICAg
IG1ha2VfdW5pcTxDb25zdGFudEZpbHRlcj4oRXhwcmVzc2lvblR5cGU6OkNPTVBBUkVfR1JFQVRF
UlRIQU4sIFZhbHVlOjpNYXhpbXVtVmFsdWUodGFyZ2V0LmNvbHVtbl90eXBlKSk7Ci0JCQl0YXJn
ZXQuZHluYW1pY19maWx0ZXJzLT5QdXNoRmlsdGVyKG9wLCB0YXJnZXQuc2Nhbl9jb2x1bW5faW5k
ZXgsIHN0ZDo6bW92ZShhbHdheXNfZmFsc2UpKTsKKwkJCXRhcmdldC5keW5hbWljX2ZpbHRlcnMt
PlB1c2hGaWx0ZXIob3AsIFByb2plY3Rpb25JbmRleCh0YXJnZXQuc2Nhbl9jb2x1bW5faW5kZXgp
LCBzdGQ6Om1vdmUoYWx3YXlzX2ZhbHNlKSk7CiAJCQlEX1BSSU5URigiW1BVU0hET1dOXSBwdXNo
ZWQgYWx3YXlzLWZhbHNlIGZvciBjb2wgJXMgKGVtcHR5IGJ1aWxkIHNpZGUpIiwgdGFyZ2V0LmNv
bHVtbl9uYW1lLmNfc3RyKCkpOwogCQl9CiAJCXJldHVybjsKQEAgLTQwMyw3ICs0MDMsNyBAQCBz
dGF0aWMgdm9pZCBQdXNoRHluYW1pY0ZpbHRlcnMoY29uc3QgUGh5c2ljYWxDcmVhdGVGaWx0ZXIg
Jm9wLCBjb25zdCBDcmVhdGVGaWx0ZQogCQkJCWF1dG8gJmNkID0gZ3NpbmsuY29sdW1uX2Rpc3Rp
bmN0W2ldOwogCQkJCWlmICghY2Qub3Zlcl90aHJlc2hvbGQgJiYgY2QudmFsdWVzLnNpemUoKSA9
PSAxKSB7CiAJCQkJCWF1dG8gZXEgPSBtYWtlX3VuaXE8Q29uc3RhbnRGaWx0ZXI+KEV4cHJlc3Np
b25UeXBlOjpDT01QQVJFX0VRVUFMLCAqY2QudmFsdWVzLmJlZ2luKCkpOwotCQkJCQl0YXJnZXQu
ZHluYW1pY19maWx0ZXJzLT5QdXNoRmlsdGVyKG9wLCB0YXJnZXQuc2Nhbl9jb2x1bW5faW5kZXgs
IHN0ZDo6bW92ZShlcSkpOworCQkJCQl0YXJnZXQuZHluYW1pY19maWx0ZXJzLT5QdXNoRmlsdGVy
KG9wLCBQcm9qZWN0aW9uSW5kZXgodGFyZ2V0LnNjYW5fY29sdW1uX2luZGV4KSwgc3RkOjptb3Zl
KGVxKSk7CiAJCQkJCXB1c2hlZF9lcXVhbCA9IHRydWU7CiAJCQkJCURfUFJJTlRGKCJbUFVTSERP
V05dIHB1c2hlZCBlcXVhbGl0eSBjb25zdGFudCBmb3IgY29sICVzIiwgdGFyZ2V0LmNvbHVtbl9u
YW1lLmNfc3RyKCkpOwogCQkJCX0gZWxzZSBpZiAoIWNkLm92ZXJfdGhyZXNob2xkICYmIGNkLnZh
bHVlcy5zaXplKCkgPiAxKSB7CkBAIC00MTEsNyArNDExLDcgQEAgc3RhdGljIHZvaWQgUHVzaER5
bmFtaWNGaWx0ZXJzKGNvbnN0IFBoeXNpY2FsQ3JlYXRlRmlsdGVyICZvcCwgY29uc3QgQ3JlYXRl
RmlsdGUKIAkJCQkJaWYgKCFGaWx0ZXJDb21iaW5lcjo6Q29udGFpbnNOdWxsKGluX2xpc3QpICYm
ICFGaWx0ZXJDb21iaW5lcjo6SXNEZW5zZVJhbmdlKGluX2xpc3QpKSB7CiAJCQkJCQlhdXRvIGlu
X2YgPSBtYWtlX3VuaXE8SW5GaWx0ZXI+KHN0ZDo6bW92ZShpbl9saXN0KSk7CiAJCQkJCQlhdXRv
IG9wdCA9IG1ha2VfdW5pcTxPcHRpb25hbEZpbHRlcj4oc3RkOjptb3ZlKGluX2YpKTsKLQkJCQkJ
CXRhcmdldC5keW5hbWljX2ZpbHRlcnMtPlB1c2hGaWx0ZXIob3AsIHRhcmdldC5zY2FuX2NvbHVt
bl9pbmRleCwgc3RkOjptb3ZlKG9wdCkpOworCQkJCQkJdGFyZ2V0LmR5bmFtaWNfZmlsdGVycy0+
UHVzaEZpbHRlcihvcCwgUHJvamVjdGlvbkluZGV4KHRhcmdldC5zY2FuX2NvbHVtbl9pbmRleCks
IHN0ZDo6bW92ZShvcHQpKTsKIAkJCQkJCURfUFJJTlRGKCJbUFVTSERPV05dIHB1c2hlZCBJTi1m
aWx0ZXIgKCVsbHUgdmFsdWVzKSBmb3IgY29sICVzIiwKIAkJCQkJCSAgICAgICAgICh1bnNpZ25l
ZCBsb25nIGxvbmcpY2QudmFsdWVzLnNpemUoKSwgdGFyZ2V0LmNvbHVtbl9uYW1lLmNfc3RyKCkp
OwogCQkJCQl9CkBAIC00MjgsNyArNDI4LDcgQEAgc3RhdGljIHZvaWQgUHVzaER5bmFtaWNGaWx0
ZXJzKGNvbnN0IFBoeXNpY2FsQ3JlYXRlRmlsdGVyICZvcCwgY29uc3QgQ3JlYXRlRmlsdGUKIAkJ
CQkJYXV0byB3cmFwcGVkID0gbWFrZV91bmlxPFNlbGVjdGl2aXR5T3B0aW9uYWxGaWx0ZXI+KHN0
ZDo6bW92ZShiZl9maWx0ZXIpLAogCQkJCQkgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgMSwKIAkJCQkJICAgICAgICAgICAgICAgICAgICAgICAgICAg
ICAgICAgICAgICAgICAgICAgICAgICAgIDEwMDAwMDApOwotCQkJCQl0YXJnZXQuZHluYW1pY19m
aWx0ZXJzLT5QdXNoRmlsdGVyKG9wLCB0YXJnZXQuc2Nhbl9jb2x1bW5faW5kZXgsIHN0ZDo6bW92
ZSh3cmFwcGVkKSk7CisJCQkJCXRhcmdldC5keW5hbWljX2ZpbHRlcnMtPlB1c2hGaWx0ZXIob3As
IFByb2plY3Rpb25JbmRleCh0YXJnZXQuc2Nhbl9jb2x1bW5faW5kZXgpLCBzdGQ6Om1vdmUod3Jh
cHBlZCkpOwogCQkJCQlEX1BSSU5URigiW1BVU0hET1dOXSBwdXNoZWQgQkYgZm9yIGNvbCAlcyB0
byBzY2FuIGNvbCAlbGx1IiwgdGFyZ2V0LmNvbHVtbl9uYW1lLmNfc3RyKCksCiAJCQkJCSAgICAg
ICAgICh1bnNpZ25lZCBsb25nIGxvbmcpdGFyZ2V0LnNjYW5fY29sdW1uX2luZGV4KTsKIAkJCQl9
CkBAIC00MzksMTAgKzQzOSwxMCBAQCBzdGF0aWMgdm9pZCBQdXNoRHluYW1pY0ZpbHRlcnMoY29u
c3QgUGh5c2ljYWxDcmVhdGVGaWx0ZXIgJm9wLCBjb25zdCBDcmVhdGVGaWx0ZQogCQkJICAgIGdz
aW5rLmNvbHVtbl9taW5fbWF4W2ldLmhhc192YWx1ZSkgewogCQkJCWF1dG8gJm1tID0gZ3Npbmsu
Y29sdW1uX21pbl9tYXhbaV07CiAJCQkJYXV0byBtaW5fZmlsdGVyID0gbWFrZV91bmlxPENvbnN0
YW50RmlsdGVyPihFeHByZXNzaW9uVHlwZTo6Q09NUEFSRV9HUkVBVEVSVEhBTk9SRVFVQUxUTywg
bW0ubWluX3ZhbCk7Ci0JCQkJdGFyZ2V0LmR5bmFtaWNfZmlsdGVycy0+UHVzaEZpbHRlcihvcCwg
dGFyZ2V0LnNjYW5fY29sdW1uX2luZGV4LCBzdGQ6Om1vdmUobWluX2ZpbHRlcikpOworCQkJCXRh
cmdldC5keW5hbWljX2ZpbHRlcnMtPlB1c2hGaWx0ZXIob3AsIFByb2plY3Rpb25JbmRleCh0YXJn
ZXQuc2Nhbl9jb2x1bW5faW5kZXgpLCBzdGQ6Om1vdmUobWluX2ZpbHRlcikpOwogCiAJCQkJYXV0
byBtYXhfZmlsdGVyID0gbWFrZV91bmlxPENvbnN0YW50RmlsdGVyPihFeHByZXNzaW9uVHlwZTo6
Q09NUEFSRV9MRVNTVEhBTk9SRVFVQUxUTywgbW0ubWF4X3ZhbCk7Ci0JCQkJdGFyZ2V0LmR5bmFt
aWNfZmlsdGVycy0+UHVzaEZpbHRlcihvcCwgdGFyZ2V0LnNjYW5fY29sdW1uX2luZGV4LCBzdGQ6
Om1vdmUobWF4X2ZpbHRlcikpOworCQkJCXRhcmdldC5keW5hbWljX2ZpbHRlcnMtPlB1c2hGaWx0
ZXIob3AsIFByb2plY3Rpb25JbmRleCh0YXJnZXQuc2Nhbl9jb2x1bW5faW5kZXgpLCBzdGQ6Om1v
dmUobWF4X2ZpbHRlcikpOwogCiAJCQkJRF9QUklOVEYoIltQVVNIRE9XTl0gcHVzaGVkIG1pbi1t
YXggZm9yIGNvbCAlcyBbJXMsICVzXSIsIHRhcmdldC5jb2x1bW5fbmFtZS5jX3N0cigpLAogCQkJ
CSAgICAgICAgIG1tLm1pbl92YWwuVG9TdHJpbmcoKS5jX3N0cigpLCBtbS5tYXhfdmFsLlRvU3Ry
aW5nKCkuY19zdHIoKSk7CkBAIC01MDEsNyArNTAxLDcgQEAgU2lua0ZpbmFsaXplVHlwZSBQaHlz
aWNhbENyZWF0ZUZpbHRlcjo6RmluYWxpemUoUGlwZWxpbmUgJnBpcGVsaW5lLCBFdmVudCAmZXZl
bnQKIAkJCWlmIChhY3R1YWxfcm93cyAqIDggPiBhbGxvY2F0ZWRfYml0cykgewogCQkJCURfUFJJ
TlRGKCJbUkVTSVpFXSBDUkVBVEVfRklMVEVSIChidWlsZD0lcykgY29sPSglbGx1LiVsbHUpIHNp
emVkX2Zvcj0lbGx1IGFjdHVhbD0lbGx1ICIKIAkJCQkgICAgICAgICAiYWxsb2NhdGVkX2JpdHM9
JWxsdSAtPiByZWhhc2hpbmciLAotCQkJCSAgICAgICAgIGJ1aWxkX3RhYmxlLmNfc3RyKCksICh1
bnNpZ25lZCBsb25nIGxvbmcpY29sLnRhYmxlX2luZGV4LAorCQkJCSAgICAgICAgIGJ1aWxkX3Rh
YmxlLmNfc3RyKCksICh1bnNpZ25lZCBsb25nIGxvbmcpY29sLnRhYmxlX2luZGV4LmluZGV4LAog
CQkJCSAgICAgICAgICh1bnNpZ25lZCBsb25nIGxvbmcpY29sLmNvbHVtbl9pbmRleCwgKHVuc2ln
bmVkIGxvbmcgbG9uZyliZi5TaXplZEZvclJvd3MoKSwKIAkJCQkgICAgICAgICAodW5zaWduZWQg
bG9uZyBsb25nKWFjdHVhbF9yb3dzLCAodW5zaWduZWQgbG9uZyBsb25nKWFsbG9jYXRlZF9iaXRz
KTsKIAkJCQliZi5SZWluaXRpYWxpemVBbmRSZWhhc2goY29udGV4dCwgYWN0dWFsX3Jvd3MsICpn
c2luay50b3RhbF9kYXRhLCB7Ym91bmRfY29sdW1uX2luZGljZXNbaV19KTsKZGlmZiAtLWdpdCBh
L3NyYy9vcGVyYXRvcnMvcGh5c2ljYWxfY3JlYXRlX2ZpbHRlci5ocHAgYi9zcmMvb3BlcmF0b3Jz
L3BoeXNpY2FsX2NyZWF0ZV9maWx0ZXIuaHBwCmluZGV4IGRkNTc0NTEuLjI3MTQ3MzcgMTAwNjQ0
Ci0tLSBhL3NyYy9vcGVyYXRvcnMvcGh5c2ljYWxfY3JlYXRlX2ZpbHRlci5ocHAKKysrIGIvc3Jj
L29wZXJhdG9ycy9waHlzaWNhbF9jcmVhdGVfZmlsdGVyLmhwcApAQCAtNiw2ICs2LDcgQEAKICNp
bmNsdWRlICJkdWNrZGIvY29tbW9uL3R5cGVzL2NvbHVtbi9jb2x1bW5fZGF0YV9jb2xsZWN0aW9u
LmhwcCIKICNpbmNsdWRlIDxkdWNrZGIvY29tbW9uL3R5cGVzL2NvbHVtbi9jb2x1bW5fZGF0YV9z
Y2FuX3N0YXRlcy5ocHA+CiAjaW5jbHVkZSAiZHVja2RiL3BsYW5uZXIvdGFibGVfZmlsdGVyLmhw
cCIKKyNpbmNsdWRlICJkdWNrZGIvcGxhbm5lci90YWJsZV9maWx0ZXJfc2V0LmhwcCIKICNpbmNs
dWRlICJkdWNrZGIvY29tbW9uL3R5cGVzL3ZhbHVlX21hcC5ocHAiCiAKIG5hbWVzcGFjZSBkdWNr
ZGIgewpkaWZmIC0tZ2l0IGEvc3JjL29wZXJhdG9ycy9waHlzaWNhbF9wcm9iZV9maWx0ZXIuY3Bw
IGIvc3JjL29wZXJhdG9ycy9waHlzaWNhbF9wcm9iZV9maWx0ZXIuY3BwCmluZGV4IDFlMjM1ZGIu
Ljg3YmJmM2MgMTAwNjQ0Ci0tLSBhL3NyYy9vcGVyYXRvcnMvcGh5c2ljYWxfcHJvYmVfZmlsdGVy
LmNwcAorKysgYi9zcmMvb3BlcmF0b3JzL3BoeXNpY2FsX3Byb2JlX2ZpbHRlci5jcHAKQEAgLTQy
LDcgKzQyLDcgQEAgSW5zZXJ0aW9uT3JkZXJQcmVzZXJ2aW5nTWFwPHN0cmluZz4gUGh5c2ljYWxQ
cm9iZUZpbHRlcjo6UGFyYW1zVG9TdHJpbmcoKSBjb25zdAogCQlpZiAoaSA+IDApIHsKIAkJCXBy
b2JlX2NvbHMgKz0gIiwgIjsKIAkJfQotCQlwcm9iZV9jb2xzICs9ICIoIiArIHRvX3N0cmluZyhm
aWx0ZXJfb3BlcmF0aW9uLT5wcm9iZV9jb2x1bW5zW2ldLnRhYmxlX2luZGV4KSArICIuIiArCisJ
CXByb2JlX2NvbHMgKz0gIigiICsgdG9fc3RyaW5nKGZpbHRlcl9vcGVyYXRpb24tPnByb2JlX2Nv
bHVtbnNbaV0udGFibGVfaW5kZXguaW5kZXgpICsgIi4iICsKIAkJICAgICAgICAgICAgICB0b19z
dHJpbmcoZmlsdGVyX29wZXJhdGlvbi0+cHJvYmVfY29sdW1uc1tpXS5jb2x1bW5faW5kZXgpICsg
IikiOwogCX0KIAlyZXN1bHRbIlByb2JlIENvbHVtbnMiXSA9IHByb2JlX2NvbHM7CkBAIC05OCw3
ICs5OCw3IEBAIE9wZXJhdG9yUmVzdWx0VHlwZSBQaHlzaWNhbFByb2JlRmlsdGVyOjpFeGVjdXRl
SW50ZXJuYWwoRXhlY3V0aW9uQ29udGV4dCAmY29udGV4CiAJCQkJCQkgICAgICAgICAgICAgICAg
ICAgICAgICAgOiAidW5rbm93biI7CiAJCQkJCQlEX1BSSU5URigKIAkJCQkJCSAgICAiW0VYRUNf
SU5URVJOQUxdIFBST0JFX0ZJTFRFUiBmb3VuZCBibG9vbSBmaWx0ZXIgZm9yIGNvbCglbGx1LCVs
bHUpIGZyb20gQ1JFQVRFX0ZJTFRFUiAoYnVpbGQ9JXMpIiwKLQkJCQkJCSAgICAodW5zaWduZWQg
bG9uZyBsb25nKWJ1aWxkX2NvbC50YWJsZV9pbmRleCwgKHVuc2lnbmVkIGxvbmcgbG9uZylidWls
ZF9jb2wuY29sdW1uX2luZGV4LAorCQkJCQkJICAgICh1bnNpZ25lZCBsb25nIGxvbmcpYnVpbGRf
Y29sLnRhYmxlX2luZGV4LmluZGV4LCAodW5zaWduZWQgbG9uZyBsb25nKWJ1aWxkX2NvbC5jb2x1
bW5faW5kZXgsCiAJCQkJCQkgICAgYnVpbGRfdGFibGUuY19zdHIoKSk7CiAJCQkJCQlzdGF0ZS5i
bG9vbV9maWx0ZXJzLnB1c2hfYmFjayhiZik7CiAJCQkJCQlicmVhazsgLy8gZm91bmQgdGhlIGZp
bHRlciBmb3IgdGhpcyBjb2x1bW4KZGlmZiAtLWdpdCBhL3NyYy9vcHRpbWl6ZXIvZ3JhcGhfbWFu
YWdlci5ocHAgYi9zcmMvb3B0aW1pemVyL2dyYXBoX21hbmFnZXIuaHBwCmluZGV4IGQwZjRiNWUu
LjlkY2YyYjQgMTAwNjQ0Ci0tLSBhL3NyYy9vcHRpbWl6ZXIvZ3JhcGhfbWFuYWdlci5ocHAKKysr
IGIvc3JjL29wdGltaXplci9ncmFwaF9tYW5hZ2VyLmhwcApAQCAtMTEsNyArMTEsNyBAQCBuYW1l
c3BhY2UgZHVja2RiIHsKIC8vIGhhc2ggZnVuY3Rpb24gZm9yIENvbHVtbkJpbmRpbmcgdG8gdXNl
IGFzIG1hcCBrZXkKIHN0cnVjdCBDb2x1bW5CaW5kaW5nSGFzaCB7CiAJc2l6ZV90IG9wZXJhdG9y
KCkoY29uc3QgQ29sdW1uQmluZGluZyAmYmluZGluZykgY29uc3QgewotCQlyZXR1cm4gc3RkOjpo
YXNoPGlkeF90PigpKGJpbmRpbmcudGFibGVfaW5kZXgpIF4gKHN0ZDo6aGFzaDxpZHhfdD4oKShi
aW5kaW5nLmNvbHVtbl9pbmRleCkgPDwgMTYpOworCQlyZXR1cm4gc3RkOjpoYXNoPFRhYmxlSW5k
ZXg+KCkoYmluZGluZy50YWJsZV9pbmRleCkgXiAoc3RkOjpoYXNoPGlkeF90PigpKGJpbmRpbmcu
Y29sdW1uX2luZGV4KSA8PCAxNik7CiAJfQogfTsKIApkaWZmIC0tZ2l0IGEvc3JjL29wdGltaXpl
ci9yb2J1c3Rfb3B0aW1pemVyLmNwcCBiL3NyYy9vcHRpbWl6ZXIvcm9idXN0X29wdGltaXplci5j
cHAKaW5kZXggODY1MmQxNC4uZWRmNTEyNiAxMDA2NDQKLS0tIGEvc3JjL29wdGltaXplci9yb2J1
c3Rfb3B0aW1pemVyLmNwcAorKysgYi9zcmMvb3B0aW1pemVyL3JvYnVzdF9vcHRpbWl6ZXIuY3Bw
CkBAIC01Nyw4ICs1Nyw4IEBAIHZvaWQgUm9idXN0T3B0aW1pemVyQ29udGV4dFN0YXRlOjpFeHRy
YWN0T3BlcmF0b3JzUmVjdXJzaXZlKExvZ2ljYWxPcGVyYXRvciAmcGxhCiAJCWNhc2UgSm9pblR5
cGU6OlJJR0hUX1NFTUk6IHsKIAkJCWlmIChzdGQ6OmFueV9vZihqb2luLmNvbmRpdGlvbnMuYmVn
aW4oKSwgam9pbi5jb25kaXRpb25zLmVuZCgpLCBbXShjb25zdCBKb2luQ29uZGl0aW9uICZqYykg
ewogCQkJCSAgICByZXR1cm4gamMuR2V0Q29tcGFyaXNvblR5cGUoKSA9PSBFeHByZXNzaW9uVHlw
ZTo6Q09NUEFSRV9FUVVBTCAmJgotCQkJCSAgICAgICAgICAgamMuR2V0TEhTKCkudHlwZSA9PSBF
eHByZXNzaW9uVHlwZTo6Qk9VTkRfQ09MVU1OX1JFRiAmJgotCQkJCSAgICAgICAgICAgamMuR2V0
UkhTKCkudHlwZSA9PSBFeHByZXNzaW9uVHlwZTo6Qk9VTkRfQ09MVU1OX1JFRjsKKwkJCQkgICAg
ICAgICAgIGpjLkdldExIUygpLkdldEV4cHJlc3Npb25UeXBlKCkgPT0gRXhwcmVzc2lvblR5cGU6
OkJPVU5EX0NPTFVNTl9SRUYgJiYKKwkJCQkgICAgICAgICAgIGpjLkdldFJIUygpLkdldEV4cHJl
c3Npb25UeXBlKCkgPT0gRXhwcmVzc2lvblR5cGU6OkJPVU5EX0NPTFVNTl9SRUY7CiAJCQkgICAg
fSkpIHsKIAkJCQkvLyBKb2luRWRnZSBlZGdlKGpvaW4pOwogCQkJCWpvaW5fb3BzLnB1c2hfYmFj
ayhvcCk7CkBAIC04OSw3ICs4OSw3IEBAIHZvaWQgUm9idXN0T3B0aW1pemVyQ29udGV4dFN0YXRl
OjpFeHRyYWN0T3BlcmF0b3JzUmVjdXJzaXZlKExvZ2ljYWxPcGVyYXRvciAmcGxhCiAJCX0gZWxz
ZSB7CiAJCQlhdXRvIG9sZF9yZWZzID0gYWdnLkdldENvbHVtbkJpbmRpbmdzKCk7CiAJCQlmb3Ig
KHNpemVfdCBpID0gMDsgaSA8IGFnZy5ncm91cHMuc2l6ZSgpOyBpKyspIHsKLQkJCQlpZiAoYWdn
Lmdyb3Vwc1tpXS0+dHlwZSA9PSBFeHByZXNzaW9uVHlwZTo6Qk9VTkRfQ09MVU1OX1JFRikgewor
CQkJCWlmIChhZ2cuZ3JvdXBzW2ldLT5HZXRFeHByZXNzaW9uVHlwZSgpID09IEV4cHJlc3Npb25U
eXBlOjpCT1VORF9DT0xVTU5fUkVGKSB7CiAJCQkJCWF1dG8gJmNvbF9yZWYgPSBhZ2cuZ3JvdXBz
W2ldLT5DYXN0PEJvdW5kQ29sdW1uUmVmRXhwcmVzc2lvbj4oKTsKIAkJCQkJcmVuYW1lX2NvbF9i
aW5kaW5ncy5pbnNlcnQoe29sZF9yZWZzW2ldLCBjb2xfcmVmLmJpbmRpbmd9KTsKIAkJCQl9CkBA
IC0xMDEsNyArMTAxLDcgQEAgdm9pZCBSb2J1c3RPcHRpbWl6ZXJDb250ZXh0U3RhdGU6OkV4dHJh
Y3RPcGVyYXRvcnNSZWN1cnNpdmUoTG9naWNhbE9wZXJhdG9yICZwbGEKIAljYXNlIExvZ2ljYWxP
cGVyYXRvclR5cGU6OkxPR0lDQUxfUFJPSkVDVElPTjogewogCQlhdXRvIG9sZF9yZWZzID0gb3At
PkdldENvbHVtbkJpbmRpbmdzKCk7CiAJCWZvciAoc2l6ZV90IGkgPSAwOyBpIDwgb3AtPmV4cHJl
c3Npb25zLnNpemUoKTsgaSsrKSB7Ci0JCQlpZiAob3AtPmV4cHJlc3Npb25zW2ldLT50eXBlID09
IEV4cHJlc3Npb25UeXBlOjpCT1VORF9DT0xVTU5fUkVGKSB7CisJCQlpZiAob3AtPmV4cHJlc3Np
b25zW2ldLT5HZXRFeHByZXNzaW9uVHlwZSgpID09IEV4cHJlc3Npb25UeXBlOjpCT1VORF9DT0xV
TU5fUkVGKSB7CiAJCQkJYXV0byAmY29sX3JlZiA9IG9wLT5leHByZXNzaW9uc1tpXS0+Q2FzdDxC
b3VuZENvbHVtblJlZkV4cHJlc3Npb24+KCk7CiAJCQkJcmVuYW1lX2NvbF9iaW5kaW5ncy5pbnNl
cnQoe29sZF9yZWZzW2ldLCBjb2xfcmVmLmJpbmRpbmd9KTsKIAkJCX0KQEAgLTE0NCwxMCArMTQ0
LDEwIEBAIENvbHVtbkJpbmRpbmcgUm9idXN0T3B0aW1pemVyQ29udGV4dFN0YXRlOjpSZXNvbHZl
Q29sdW1uQmluZGluZyhjb25zdCBDb2x1bW5CaW5kCiAKIAkvLyBmb2xsb3cgdGhlIHJlbmFtZSBj
aGFpbiB1bnRpbCB3ZSBmaW5kIGEgYmFzZSB0YWJsZSBiaW5kaW5nCiAJd2hpbGUgKHRydWUpIHsK
LQkJYXV0byBrZXkgPSBtYWtlX3BhaXIoY3VycmVudC50YWJsZV9pbmRleCwgY3VycmVudC5jb2x1
bW5faW5kZXgpOworCQlhdXRvIGtleSA9IG1ha2VfcGFpcihjdXJyZW50LnRhYmxlX2luZGV4Lmlu
ZGV4LCBjdXJyZW50LmNvbHVtbl9pbmRleCk7CiAJCWlmICh2aXNpdGVkLmNvdW50KGtleSkpIHsK
IAkJCURfUFJJTlRGKCJXQVJOSU5HOiBDeWNsZSBkZXRlY3RlZCBpbiByZW5hbWVfY29sX2JpbmRp
bmdzIGZvciBiaW5kaW5nICglbGx1LiVsbHUpIiwKLQkJCSAgICAgICAgICh1bnNpZ25lZCBsb25n
IGxvbmcpY3VycmVudC50YWJsZV9pbmRleCwgKHVuc2lnbmVkIGxvbmcgbG9uZyljdXJyZW50LmNv
bHVtbl9pbmRleCk7CisJCQkgICAgICAgICAodW5zaWduZWQgbG9uZyBsb25nKWN1cnJlbnQudGFi
bGVfaW5kZXguaW5kZXgsICh1bnNpZ25lZCBsb25nIGxvbmcpY3VycmVudC5jb2x1bW5faW5kZXgp
OwogCQkJYnJlYWs7CiAJCX0KIAkJdmlzaXRlZC5pbnNlcnQoa2V5KTsKQEAgLTE3NSw4ICsxNzUs
OCBAQCB2ZWN0b3I8Sm9pbkVkZ2U+IFJvYnVzdE9wdGltaXplckNvbnRleHRTdGF0ZTo6Q3JlYXRl
Sm9pbkVkZ2VzKHZlY3RvcjxMb2dpY2FsT3BlcgogCiAJCWZvciAoY29uc3QgSm9pbkNvbmRpdGlv
biAmY29uZCA6IGpvaW4uY29uZGl0aW9ucykgewogCQkJaWYgKGNvbmQuR2V0Q29tcGFyaXNvblR5
cGUoKSA9PSBFeHByZXNzaW9uVHlwZTo6Q09NUEFSRV9FUVVBTCAmJgotCQkJICAgIGNvbmQuR2V0
TEhTKCkudHlwZSA9PSBFeHByZXNzaW9uVHlwZTo6Qk9VTkRfQ09MVU1OX1JFRiAmJgotCQkJICAg
IGNvbmQuR2V0UkhTKCkudHlwZSA9PSBFeHByZXNzaW9uVHlwZTo6Qk9VTkRfQ09MVU1OX1JFRikg
eworCQkJICAgIGNvbmQuR2V0TEhTKCkuR2V0RXhwcmVzc2lvblR5cGUoKSA9PSBFeHByZXNzaW9u
VHlwZTo6Qk9VTkRfQ09MVU1OX1JFRiAmJgorCQkJICAgIGNvbmQuR2V0UkhTKCkuR2V0RXhwcmVz
c2lvblR5cGUoKSA9PSBFeHByZXNzaW9uVHlwZTo6Qk9VTkRfQ09MVU1OX1JFRikgewogCQkJCS8v
IHN0b3JlIG9yaWdpbmFsIGJpbmRpbmdzCiAJCQkJQ29sdW1uQmluZGluZyBsZWZ0X2JpbmRpbmcg
PSBjb25kLkdldExIUygpLkNhc3Q8Qm91bmRDb2x1bW5SZWZFeHByZXNzaW9uPigpLmJpbmRpbmc7
CiAJCQkJQ29sdW1uQmluZGluZyByaWdodF9iaW5kaW5nID0gY29uZC5HZXRSSFMoKS5DYXN0PEJv
dW5kQ29sdW1uUmVmRXhwcmVzc2lvbj4oKS5iaW5kaW5nOwpAQCAtMTkyLDggKzE5Miw4IEBAIHZl
Y3RvcjxKb2luRWRnZT4gUm9idXN0T3B0aW1pemVyQ29udGV4dFN0YXRlOjpDcmVhdGVKb2luRWRn
ZXModmVjdG9yPExvZ2ljYWxPcGVyCiAKIAkJaWYgKCFsZWZ0X2NvbHVtbnMuZW1wdHkoKSAmJiAh
cmlnaHRfY29sdW1ucy5lbXB0eSgpKSB7CiAJCQkvLyBnZXQgdGFibGUgaW5kaWNlcyBmcm9tIGZp
cnN0IHJlc29sdmVkIGNvbHVtbgotCQkJaWR4X3QgbGVmdF90YWJsZV9pZHggPSByZXNvbHZlZF9s
ZWZ0X2NvbHVtbnNbMF0udGFibGVfaW5kZXg7Ci0JCQlpZHhfdCByaWdodF90YWJsZV9pZHggPSBy
ZXNvbHZlZF9yaWdodF9jb2x1bW5zWzBdLnRhYmxlX2luZGV4OworCQkJaWR4X3QgbGVmdF90YWJs
ZV9pZHggPSByZXNvbHZlZF9sZWZ0X2NvbHVtbnNbMF0udGFibGVfaW5kZXguaW5kZXg7CisJCQlp
ZHhfdCByaWdodF90YWJsZV9pZHggPSByZXNvbHZlZF9yaWdodF9jb2x1bW5zWzBdLnRhYmxlX2lu
ZGV4LmluZGV4OwogCiAJCQkvLyB2ZXJpZnkgdGhlc2UgdGFibGUgaW5kaWNlcyBleGlzdCBpbiBv
dXIgdGFibGUgbWFuYWdlcgogCQkJaWYgKHRhYmxlX21nci50YWJsZV9sb29rdXAuZmluZChsZWZ0
X3RhYmxlX2lkeCkgIT0gdGFibGVfbWdyLnRhYmxlX2xvb2t1cC5lbmQoKSAmJgpAQCAtNDA3LDEz
ICs0MDcsMTMgQEAgdm9pZCBSb2J1c3RPcHRpbWl6ZXJDb250ZXh0U3RhdGU6OkRlYnVnUHJpbnRH
cmFwaChjb25zdCB2ZWN0b3I8Sm9pbkVkZ2U+ICZlZGdlcykKIAkJLy8gUHJpbnQgY29sdW1uIGJp
bmRpbmdzCiAJCXN0cmluZyBjb2xzX2EgPSAiICBDb2x1bW5zIEE6ICI7CiAJCWZvciAoY29uc3Qg
YXV0byAmY29sIDogZWRnZS5qb2luX2NvbHVtbnNfYSkgewotCQkJY29sc19hICs9ICIoIiArIHN0
ZDo6dG9fc3RyaW5nKGNvbC50YWJsZV9pbmRleCkgKyAiLiIgKyBzdGQ6OnRvX3N0cmluZyhjb2wu
Y29sdW1uX2luZGV4KSArICIpICI7CisJCQljb2xzX2EgKz0gIigiICsgc3RkOjp0b19zdHJpbmco
Y29sLnRhYmxlX2luZGV4LmluZGV4KSArICIuIiArIHN0ZDo6dG9fc3RyaW5nKGNvbC5jb2x1bW5f
aW5kZXgpICsgIikgIjsKIAkJfQogCQlQcmludGVyOjpQcmludChjb2xzX2EpOwogCiAJCXN0cmlu
ZyBjb2xzX2IgPSAiICBDb2x1bW5zIEI6ICI7CiAJCWZvciAoY29uc3QgYXV0byAmY29sIDogZWRn
ZS5qb2luX2NvbHVtbnNfYikgewotCQkJY29sc19iICs9ICIoIiArIHN0ZDo6dG9fc3RyaW5nKGNv
bC50YWJsZV9pbmRleCkgKyAiLiIgKyBzdGQ6OnRvX3N0cmluZyhjb2wuY29sdW1uX2luZGV4KSAr
ICIpICI7CisJCQljb2xzX2IgKz0gIigiICsgc3RkOjp0b19zdHJpbmcoY29sLnRhYmxlX2luZGV4
LmluZGV4KSArICIuIiArIHN0ZDo6dG9fc3RyaW5nKGNvbC5jb2x1bW5faW5kZXgpICsgIikgIjsK
IAkJfQogCQlQcmludGVyOjpQcmludChjb2xzX2IpOwogCX0KQEAgLTQ0Myw3ICs0NDMsNyBAQCB2
b2lkIFJvYnVzdE9wdGltaXplckNvbnRleHRTdGF0ZTo6RGVidWdQcmludE1TVChjb25zdCB2ZWN0
b3I8Sm9pbkVkZ2U+ICZtc3RfZWRnZQogCQkJUHJpbnRlcjo6UHJpbnRGKCJGaWx0ZXIgT3AgJXp1
OiBDUkVBVEVfRklMVEVSIG9uIHRhYmxlICVsbHUiLCBpLCAodW5zaWduZWQgbG9uZyBsb25nKWZp
bHRlcl9vcC5idWlsZF90YWJsZV9pZHgpOwogCQkJc3RyaW5nIGNvbHMgPSAiICBCdWlsZCBjb2x1
bW5zOiAiOwogCQkJZm9yIChjb25zdCBhdXRvICZjb2wgOiBmaWx0ZXJfb3AuYnVpbGRfY29sdW1u
cykgewotCQkJCWNvbHMgKz0gIigiICsgc3RkOjp0b19zdHJpbmcoY29sLnRhYmxlX2luZGV4KSAr
ICIuIiArIHN0ZDo6dG9fc3RyaW5nKGNvbC5jb2x1bW5faW5kZXgpICsgIikgIjsKKwkJCQljb2xz
ICs9ICIoIiArIHN0ZDo6dG9fc3RyaW5nKGNvbC50YWJsZV9pbmRleC5pbmRleCkgKyAiLiIgKyBz
dGQ6OnRvX3N0cmluZyhjb2wuY29sdW1uX2luZGV4KSArICIpICI7CiAJCQl9CiAJCQlQcmludGVy
OjpQcmludChjb2xzKTsKIAkJfSBlbHNlIHsKQEAgLTQ1MiwxMyArNDUyLDEzIEBAIHZvaWQgUm9i
dXN0T3B0aW1pemVyQ29udGV4dFN0YXRlOjpEZWJ1Z1ByaW50TVNUKGNvbnN0IHZlY3RvcjxKb2lu
RWRnZT4gJm1zdF9lZGdlCiAJCQkgICAgICAgICAgICAgICAgKHVuc2lnbmVkIGxvbmcgbG9uZylm
aWx0ZXJfb3AucHJvYmVfdGFibGVfaWR4LCAodW5zaWduZWQgbG9uZyBsb25nKWZpbHRlcl9vcC5i
dWlsZF90YWJsZV9pZHgpOwogCQkJc3RyaW5nIGJ1aWxkX2NvbHMgPSAiICBCdWlsZCBjb2x1bW5z
OiAiOwogCQkJZm9yIChjb25zdCBhdXRvICZjb2wgOiBmaWx0ZXJfb3AuYnVpbGRfY29sdW1ucykg
ewotCQkJCWJ1aWxkX2NvbHMgKz0gIigiICsgc3RkOjp0b19zdHJpbmcoY29sLnRhYmxlX2luZGV4
KSArICIuIiArIHN0ZDo6dG9fc3RyaW5nKGNvbC5jb2x1bW5faW5kZXgpICsgIikgIjsKKwkJCQli
dWlsZF9jb2xzICs9ICIoIiArIHN0ZDo6dG9fc3RyaW5nKGNvbC50YWJsZV9pbmRleC5pbmRleCkg
KyAiLiIgKyBzdGQ6OnRvX3N0cmluZyhjb2wuY29sdW1uX2luZGV4KSArICIpICI7CiAJCQl9CiAJ
CQlQcmludGVyOjpQcmludChidWlsZF9jb2xzKTsKIAogCQkJc3RyaW5nIHByb2JlX2NvbHMgPSAi
ICBQcm9iZSBjb2x1bW5zOiAiOwogCQkJZm9yIChjb25zdCBhdXRvICZjb2wgOiBmaWx0ZXJfb3Au
cHJvYmVfY29sdW1ucykgewotCQkJCXByb2JlX2NvbHMgKz0gIigiICsgc3RkOjp0b19zdHJpbmco
Y29sLnRhYmxlX2luZGV4KSArICIuIiArIHN0ZDo6dG9fc3RyaW5nKGNvbC5jb2x1bW5faW5kZXgp
ICsgIikgIjsKKwkJCQlwcm9iZV9jb2xzICs9ICIoIiArIHN0ZDo6dG9fc3RyaW5nKGNvbC50YWJs
ZV9pbmRleC5pbmRleCkgKyAiLiIgKyBzdGQ6OnRvX3N0cmluZyhjb2wuY29sdW1uX2luZGV4KSAr
ICIpICI7CiAJCQl9CiAJCQlQcmludGVyOjpQcmludChwcm9iZV9jb2xzKTsKIAkJfQpAQCAtNTU4
LDggKzU1OCw4IEBAIHN0YXRpYyB2b2lkIFBoeXNpY2FsREFHREZTKExvZ2ljYWxPcGVyYXRvciAq
b3AsIFRhYmxlTWFuYWdlciAmdGFibGVfbWdyLCBSb2J1c3RPCiAJCQlpZiAoY29uZC5HZXRDb21w
YXJpc29uVHlwZSgpICE9IEV4cHJlc3Npb25UeXBlOjpDT01QQVJFX0VRVUFMKSB7CiAJCQkJY29u
dGludWU7CiAJCQl9Ci0JCQlpZiAoY29uZC5HZXRMSFMoKS50eXBlICE9IEV4cHJlc3Npb25UeXBl
OjpCT1VORF9DT0xVTU5fUkVGIHx8Ci0JCQkgICAgY29uZC5HZXRSSFMoKS50eXBlICE9IEV4cHJl
c3Npb25UeXBlOjpCT1VORF9DT0xVTU5fUkVGKSB7CisJCQlpZiAoY29uZC5HZXRMSFMoKS5HZXRF
eHByZXNzaW9uVHlwZSgpICE9IEV4cHJlc3Npb25UeXBlOjpCT1VORF9DT0xVTU5fUkVGIHx8CisJ
CQkgICAgY29uZC5HZXRSSFMoKS5HZXRFeHByZXNzaW9uVHlwZSgpICE9IEV4cHJlc3Npb25UeXBl
OjpCT1VORF9DT0xVTU5fUkVGKSB7CiAJCQkJY29udGludWU7CiAJCQl9CiAKQEAgLTU2OSwxMiAr
NTY5LDEyIEBAIHN0YXRpYyB2b2lkIFBoeXNpY2FsREFHREZTKExvZ2ljYWxPcGVyYXRvciAqb3As
IFRhYmxlTWFuYWdlciAmdGFibGVfbWdyLCBSb2J1c3RPCiAJCQkgICAgc3RhdGUuUmVzb2x2ZUNv
bHVtbkJpbmRpbmcoY29uZC5HZXRSSFMoKS5DYXN0PEJvdW5kQ29sdW1uUmVmRXhwcmVzc2lvbj4o
KS5iaW5kaW5nKTsKIAogCQkJLy8gYWRkIHRvIGVxdWl2YWxlbmNlIGNsYXNzZXMKLQkJCUNvbEtl
eSBsZWZ0X2tleSA9IHtsZWZ0X3Jlc29sdmVkLnRhYmxlX2luZGV4LCBsZWZ0X3Jlc29sdmVkLmNv
bHVtbl9pbmRleH07Ci0JCQlDb2xLZXkgcmlnaHRfa2V5ID0ge3JpZ2h0X3Jlc29sdmVkLnRhYmxl
X2luZGV4LCByaWdodF9yZXNvbHZlZC5jb2x1bW5faW5kZXh9OworCQkJQ29sS2V5IGxlZnRfa2V5
ID0ge2xlZnRfcmVzb2x2ZWQudGFibGVfaW5kZXguaW5kZXgsIGxlZnRfcmVzb2x2ZWQuY29sdW1u
X2luZGV4fTsKKwkJCUNvbEtleSByaWdodF9rZXkgPSB7cmlnaHRfcmVzb2x2ZWQudGFibGVfaW5k
ZXguaW5kZXgsIHJpZ2h0X3Jlc29sdmVkLmNvbHVtbl9pbmRleH07CiAJCQlVRlVuaW9uKHVmX3Bh
cmVudCwgbGVmdF9rZXksIHJpZ2h0X2tleSk7CiAKLQkJCWlkeF90IHRhYmxlX2EgPSBsZWZ0X3Jl
c29sdmVkLnRhYmxlX2luZGV4OwotCQkJaWR4X3QgdGFibGVfYiA9IHJpZ2h0X3Jlc29sdmVkLnRh
YmxlX2luZGV4OworCQkJaWR4X3QgdGFibGVfYSA9IGxlZnRfcmVzb2x2ZWQudGFibGVfaW5kZXgu
aW5kZXg7CisJCQlpZHhfdCB0YWJsZV9iID0gcmlnaHRfcmVzb2x2ZWQudGFibGVfaW5kZXguaW5k
ZXg7CiAJCQlpZiAoIW5vZGVfbWFwLmNvdW50KHRhYmxlX2EpIHx8ICFub2RlX21hcC5jb3VudCh0
YWJsZV9iKSkgewogCQkJCWNvbnRpbnVlOwogCQkJfQpAQCAtNjAxLDcgKzYwMSw3IEBAIHN0YXRp
YyB2b2lkIFBoeXNpY2FsREFHREZTKExvZ2ljYWxPcGVyYXRvciAqb3AsIFRhYmxlTWFuYWdlciAm
dGFibGVfbWdyLCBSb2J1c3RPCiAJCQl9CiAKIAkJCS8vIGVxdWl2IHJlc29sdXRpb24gb24gY2hp
bGQgc2lkZTogZmluZCBzaGFsbG93ZXN0IGVxdWl2YWxlbnQgKGhpZ2hlc3QgREZTLCAhPSBwYXJl
bnQpCi0JCQlDb2xLZXkgY2hpbGRfcm9vdCA9IFVGRmluZCh1Zl9wYXJlbnQsIHtjaGlsZF9jb2wu
dGFibGVfaW5kZXgsIGNoaWxkX2NvbC5jb2x1bW5faW5kZXh9KTsKKwkJCUNvbEtleSBjaGlsZF9y
b290ID0gVUZGaW5kKHVmX3BhcmVudCwge2NoaWxkX2NvbC50YWJsZV9pbmRleC5pbmRleCwgY2hp
bGRfY29sLmNvbHVtbl9pbmRleH0pOwogCQkJaWR4X3QgYmVzdF9jaGlsZCA9IGNoaWxkX2lkeDsK
IAkJCWludCBiZXN0X2NoaWxkX2RmcyA9IGRmc19pbmRleC5jb3VudChjaGlsZF9pZHgpID8gZGZz
X2luZGV4W2NoaWxkX2lkeF0gOiAtMTsKIAkJCUNvbHVtbkJpbmRpbmcgYmVzdF9jaGlsZF9jb2wg
PSBjaGlsZF9jb2w7CkBAIC02MjUsNyArNjI1LDcgQEAgc3RhdGljIHZvaWQgUGh5c2ljYWxEQUdE
RlMoTG9naWNhbE9wZXJhdG9yICpvcCwgVGFibGVNYW5hZ2VyICZ0YWJsZV9tZ3IsIFJvYnVzdE8K
IAkJCQlpZiAoY2FuZGlkYXRlX2RmcyA+IGJlc3RfY2hpbGRfZGZzKSB7CiAJCQkJCWJlc3RfY2hp
bGQgPSBjYW5kaWRhdGU7CiAJCQkJCWJlc3RfY2hpbGRfZGZzID0gY2FuZGlkYXRlX2RmczsKLQkJ
CQkJYmVzdF9jaGlsZF9jb2wgPSBDb2x1bW5CaW5kaW5nKGtleS5maXJzdCwga2V5LnNlY29uZCk7
CisJCQkJCWJlc3RfY2hpbGRfY29sID0gQ29sdW1uQmluZGluZyhUYWJsZUluZGV4KGtleS5maXJz
dCksIFByb2plY3Rpb25JbmRleChrZXkuc2Vjb25kKSk7CiAJCQkJfQogCQkJfQogCkBAIC0xMDk5
LDcgKzEwOTksNyBAQCBSb2J1c3RPcHRpbWl6ZXJDb250ZXh0U3RhdGU6OkdlbmVyYXRlU3RhZ2VN
b2RpZmljYXRpb25zRnJvbURBRyh2ZWN0b3I8UGh5c2ljYWxEQQogCQkJCWF1dG8gKnBhcmVudF9u
b2RlID0gY2hpbGRfbm9kZS0+cGFyZW50c1tlaV07CiAKIAkJCQkvLyBkZXRlcm1pbmUgdGhlIGVx
dWl2YWxlbmNlIGNsYXNzIGZvciB0aGlzIGVkZ2UgdXNpbmcgdGhlIGZpcnN0IGNvbHVtbiBwYWly
Ci0JCQkJQ29sS2V5IHBhcmVudF9jb2xfa2V5ID0ge2VkZ2UucGFyZW50X2NvbHNbMF0udGFibGVf
aW5kZXgsIGVkZ2UucGFyZW50X2NvbHNbMF0uY29sdW1uX2luZGV4fTsKKwkJCQlDb2xLZXkgcGFy
ZW50X2NvbF9rZXkgPSB7ZWRnZS5wYXJlbnRfY29sc1swXS50YWJsZV9pbmRleC5pbmRleCwgZWRn
ZS5wYXJlbnRfY29sc1swXS5jb2x1bW5faW5kZXh9OwogCQkJCUNvbEtleSBlcXVpdl9yb290ID0g
VUZGaW5kKHVmX3BhcmVudCwgcGFyZW50X2NvbF9rZXkpOwogCiAJCQkJYXV0byBpdCA9IGVxdWl2
X2NsYXNzX2JmX3NvdXJjZS5maW5kKGVxdWl2X3Jvb3QpOwpAQCAtMTMyNCw3ICsxMzI0LDcgQEAg
dm9pZCBSb2J1c3RPcHRpbWl6ZXJDb250ZXh0U3RhdGU6OkxpbmtQcm9iZUZpbHRlclRvQ3JlYXRl
RmlsdGVyKExvZ2ljYWxPcGVyYXRvcgogCQlzaXplX3Qgb3BlcmF0b3IoKShjb25zdCBDcmVhdGVG
aWx0ZXJLZXkgJmtleSkgY29uc3QgewogCQkJc2l6ZV90IGhhc2ggPSBzdGQ6Omhhc2g8aWR4X3Q+
KCkoa2V5LmJ1aWxkX3RhYmxlX2lkeCk7CiAJCQlmb3IgKGNvbnN0IGF1dG8gJmNvbCA6IGtleS5i
dWlsZF9jb2x1bW5zKSB7Ci0JCQkJaGFzaCBePSAoc3RkOjpoYXNoPGlkeF90PigpKGNvbC50YWJs
ZV9pbmRleCkgPDwgMSk7CisJCQkJaGFzaCBePSAoc3RkOjpoYXNoPFRhYmxlSW5kZXg+KCkoY29s
LnRhYmxlX2luZGV4KSA8PCAxKTsKIAkJCQloYXNoIF49IChzdGQ6Omhhc2g8aWR4X3Q+KCkoY29s
LmNvbHVtbl9pbmRleCkgPDwgMik7CiAJCQl9CiAJCQlyZXR1cm4gaGFzaDsKQEAgLTEzNzAsNyAr
MTM3MCw3IEBAIHZvaWQgUm9idXN0T3B0aW1pemVyQ29udGV4dFN0YXRlOjpMaW5rUHJvYmVGaWx0
ZXJUb0NyZWF0ZUZpbHRlcihMb2dpY2FsT3BlcmF0b3IKIAkJCQlpZiAoaXQgIT0gY3JlYXRlX2Zp
bHRlcl9ieV90YWJsZS5lbmQoKSkgewogCQkJCQlmb3IgKGF1dG8gKmNyZWF0ZV9maWx0ZXIgOiBp
dC0+c2Vjb25kKSB7CiAJCQkJCQlmb3IgKGNvbnN0IGF1dG8gJnBjIDogY3JlYXRlX2ZpbHRlci0+
ZmlsdGVyX29wZXJhdGlvbi5wcm9iZV9jb2x1bW5zKSB7Ci0JCQkJCQkJaWYgKHBjLnRhYmxlX2lu
ZGV4ID09IHByb2JlX3RhYmxlX2lkeCkgeworCQkJCQkJCWlmIChwYy50YWJsZV9pbmRleC5pbmRl
eCA9PSBwcm9iZV90YWJsZV9pZHgpIHsKIAkJCQkJCQkJcHJvYmVfZmlsdGVyLT5yZWxhdGVkX2Ny
ZWF0ZV9maWx0ZXIgPSBjcmVhdGVfZmlsdGVyOwogCQkJCQkJCQljcmVhdGVfZmlsdGVyLT5yZWxh
dGVkX3Byb2JlX2ZpbHRlci5wdXNoX2JhY2socHJvYmVfZmlsdGVyKTsKIAkJCQkJCQkJYnJlYWs7
CkBAIC0xNDY1LDcgKzE0NjUsNyBAQCB2b2lkIFJvYnVzdE9wdGltaXplckNvbnRleHRTdGF0ZTo6
U2V0dXBEeW5hbWljRmlsdGVyUHVzaGRvd24oTG9naWNhbE9wZXJhdG9yICpwbAogCQkJCWlkeF90
IHNjYW5fY29sX2lkeCA9IHByb2JlX2NvbC5jb2x1bW5faW5kZXg7CiAJCQkJaWYgKHNjYW5fY29s
X2lkeCA+PSBjb2xfaWRzLnNpemUoKSkgewogCQkJCQlEX1BSSU5URigiW1BVU0hET1dOXSBwcm9i
ZSBjb2x1bW4gKCVsbHUuJWxsdSkgb3V0IG9mIGJvdW5kcyBmb3Igc2NhbiBjb2x1bW5faWRzIChz
aXplPSV6dSkiLAotCQkJCQkgICAgICAgICAodW5zaWduZWQgbG9uZyBsb25nKXByb2JlX2NvbC50
YWJsZV9pbmRleCwgKHVuc2lnbmVkIGxvbmcgbG9uZylwcm9iZV9jb2wuY29sdW1uX2luZGV4LAor
CQkJCQkgICAgICAgICAodW5zaWduZWQgbG9uZyBsb25nKXByb2JlX2NvbC50YWJsZV9pbmRleC5p
bmRleCwgKHVuc2lnbmVkIGxvbmcgbG9uZylwcm9iZV9jb2wuY29sdW1uX2luZGV4LAogCQkJCQkg
ICAgICAgICBjb2xfaWRzLnNpemUoKSk7CiAJCQkJCWNvbnRpbnVlOwogCQkJCX0KZGlmZiAtLWdp
dCBhL3NyYy9vcHRpbWl6ZXIvdGFibGVfbWFuYWdlci5jcHAgYi9zcmMvb3B0aW1pemVyL3RhYmxl
X21hbmFnZXIuY3BwCmluZGV4IDA1YWUwMDAuLmU0YWRkMTggMTAwNjQ0Ci0tLSBhL3NyYy9vcHRp
bWl6ZXIvdGFibGVfbWFuYWdlci5jcHAKKysrIGIvc3JjL29wdGltaXplci90YWJsZV9tYW5hZ2Vy
LmNwcApAQCAtNDgsMTMgKzQ4LDEzIEBAIGlkeF90IFRhYmxlTWFuYWdlcjo6R2V0U2NhbGFyVGFi
bGVJbmRleChMb2dpY2FsT3BlcmF0b3IgKm9wKSB7CiAJY2FzZSBMb2dpY2FsT3BlcmF0b3JUeXBl
OjpMT0dJQ0FMX1VOSU9OOgogCWNhc2UgTG9naWNhbE9wZXJhdG9yVHlwZTo6TE9HSUNBTF9FWENF
UFQ6CiAJY2FzZSBMb2dpY2FsT3BlcmF0b3JUeXBlOjpMT0dJQ0FMX0lOVEVSU0VDVDogewotCQly
ZXR1cm4gb3AtPkdldFRhYmxlSW5kZXgoKVswXTsKKwkJcmV0dXJuIG9wLT5HZXRUYWJsZUluZGV4
KClbMF0uaW5kZXg7CiAJfQogCWNhc2UgTG9naWNhbE9wZXJhdG9yVHlwZTo6TE9HSUNBTF9GSUxU
RVI6IHsKIAkJcmV0dXJuIEdldFNjYWxhclRhYmxlSW5kZXgob3AtPmNoaWxkcmVuWzBdLmdldCgp
KTsKIAl9CiAJY2FzZSBMb2dpY2FsT3BlcmF0b3JUeXBlOjpMT0dJQ0FMX0FHR1JFR0FURV9BTkRf
R1JPVVBfQlk6IHsKLQkJcmV0dXJuIG9wLT5HZXRUYWJsZUluZGV4KClbMV07CisJCXJldHVybiBv
cC0+R2V0VGFibGVJbmRleCgpWzFdLmluZGV4OwogCX0KIAlkZWZhdWx0OgogCQlyZXR1cm4gc3Rk
OjpudW1lcmljX2xpbWl0czxpZHhfdD46Om1heCgpOwpkaWZmIC0tZ2l0IGEvc3JjL3RyYW5zZmVy
X2dyYXBoX21hbmFnZXIuaHBwIGIvc3JjL3RyYW5zZmVyX2dyYXBoX21hbmFnZXIuaHBwCmluZGV4
IGVhNjAxOWMuLjg1OGRjZWMgMTAwNjQ0Ci0tLSBhL3NyYy90cmFuc2Zlcl9ncmFwaF9tYW5hZ2Vy
LmhwcAorKysgYi9zcmMvdHJhbnNmZXJfZ3JhcGhfbWFuYWdlci5ocHAKQEAgLTY1LDcgKzY1LDcg
QEAgc3RydWN0IEpvaW5LZXlUYWJsZUdyb3VwIHsKIAogc3RydWN0IENvbHVtbkJpbmRpbmdIYXNo
RnVuYyB7CiAJc2l6ZV90IG9wZXJhdG9yKCkoY29uc3QgQ29sdW1uQmluZGluZyAma2V5KSBjb25z
dCB7Ci0JCXJldHVybiBzdGQ6Omhhc2g8dWludDY0X3Q+IHt9KGtleS50YWJsZV9pbmRleCkgXiAo
c3RkOjpoYXNoPHVpbnQ2NF90PiB7fShrZXkuY29sdW1uX2luZGV4KSA8PCAxKTsKKwkJcmV0dXJu
IHN0ZDo6aGFzaDxUYWJsZUluZGV4PiB7fShrZXkudGFibGVfaW5kZXgpIF4gKHN0ZDo6aGFzaDx1
aW50NjRfdD4ge30oa2V5LmNvbHVtbl9pbmRleCkgPDwgMSk7CiAJfQogfTsKIAo=
PATCH_B64
fi

log_success "Extension patch files created"

# Step 5: Install vcpkg dependencies
if [ "$SKIP_VCPKG" = false ]; then
    log_info "Step 5: Installing vcpkg dependencies (this takes 15-20 minutes)..."
    cd "$VCPKG_DIR"
    
    log_info "Installing AWS SDK (~5 min)..."
    ./vcpkg install aws-sdk-cpp[core,s3,transfer,config,sts,sso,identity-management]
    
    log_info "Installing Azure SDK (~3 min)..."
    ./vcpkg install azure-storage-blobs-cpp azure-storage-files-datalake-cpp azure-identity-cpp
    
    log_info "Installing Roaring..."
    ./vcpkg install roaring
    
    log_info "Installing libmariadb (for mysql_scanner)..."
    ./vcpkg install libmariadb

    if [ "$WITH_SPATIAL" = true ]; then
        log_info "Installing spatial dependencies (GDAL/PROJ/GEOS/SQLite)..."
        ./vcpkg install gdal[network,geos] proj geos expat sqlite3[rtree] curl openssl zlib
    fi
    if [ "$WITH_ROBUST_RPT" = true ]; then
        log_info "Installing robust RPT dependencies (OpenSSL)..."
        ./vcpkg install openssl
    fi
    
    log_success "vcpkg dependencies installed"
    cd "$DUCKDB_DIR"
else
    log_warning "Skipping vcpkg dependency installation (--skip-vcpkg)"
fi

# Step 6: Configure build
log_info "Step 6: Configuring CMake (fetches extensions)..."
BUILD_DIR="$DUCKDB_DIR/build/release-static"
mkdir -p "$BUILD_DIR"
cd "$BUILD_DIR"
sanitize_dirty_fetchcontent_deps
cd "$DUCKDB_DIR"

# Create minimal vcpkg.json to avoid manifest mode issues
echo '{"name":"duckdb","version":"1.0.0"}' > vcpkg.json

BUILD_EXTENSIONS="autocomplete;icu;tpcds;tpch;fts;json;parquet;sqlite_scanner;postgres_scanner;mysql_scanner;httpfs;excel;vss;inet;avro;aws;azure;iceberg;ducklake;delta;unity_catalog"
EXPECTED_EXTENSIONS=24
if [ "$WITH_SPATIAL" = true ]; then
    BUILD_EXTENSIONS="${BUILD_EXTENSIONS};spatial"
    EXPECTED_EXTENSIONS=$((EXPECTED_EXTENSIONS + 1))
fi
if [ "$WITH_ROBUST_RPT" = true ]; then
    BUILD_EXTENSIONS="${BUILD_EXTENSIONS};robust"
    EXPECTED_EXTENSIONS=$((EXPECTED_EXTENSIONS + 1))
fi

# Note: --allow-multiple-definition is required because postgres_scanner and mysql_scanner
# share some common helper functions (EscapeConnectionString, GetSecret, CatalogTypeIsSupported)
cmake -S "$DUCKDB_DIR" -B "$BUILD_DIR" \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_TOOLCHAIN_FILE="$VCPKG_DIR/scripts/buildsystems/vcpkg.cmake" \
  -DVCPKG_MANIFEST_MODE=OFF \
  -DCMAKE_EXE_LINKER_FLAGS="-Wl,--allow-multiple-definition" \
  -DCMAKE_SHARED_LINKER_FLAGS="-Wl,--allow-multiple-definition" \
  -DBUILD_EXTENSIONS="$BUILD_EXTENSIONS" \
  .
log_success "CMake configuration complete"

cd "$BUILD_DIR"

# Step 7: Merge vcpkg dependencies
log_info "Step 7: Merging vcpkg dependencies..."
mkdir -p vcpkg_installed/x64-linux

# Copy from global vcpkg
if [ -d "$VCPKG_DIR/installed/x64-linux" ]; then
    log_info "Copying from global vcpkg..."
    cp -r "$VCPKG_DIR/installed/x64-linux"/* vcpkg_installed/x64-linux/ 2>/dev/null || true
fi

# Merge extension-specific vcpkg directories
log_info "Merging extension-specific vcpkg directories..."
shopt -s nullglob
for ext_dir in _deps/*_extension_fc-src _deps/*_extension-src; do
    if [ -d "$ext_dir/vcpkg_installed/x64-linux" ]; then
        ext_name=$(basename "$ext_dir" | sed 's/_extension_fc-src//' | sed 's/_extension-src//')
        log_info "  Merging $ext_name..."
        cp -r "$ext_dir/vcpkg_installed/x64-linux"/* vcpkg_installed/x64-linux/ 2>/dev/null || true
    fi
done
shopt -u nullglob
log_success "vcpkg dependencies merged"

if [ "$WITH_SPATIAL" = true ]; then
    SPATIAL_PROJ_DB="$VCPKG_DIR/installed/x64-linux/share/proj/proj.db"
    SPATIAL_PROJ_DIR="$BUILD_DIR/_deps/spatial_extension_fc-src/src/spatial/modules/proj"
    SPATIAL_PROJ_MODULE="$SPATIAL_PROJ_DIR/proj_module.cpp"
    if [ ! -f "$SPATIAL_PROJ_DB" ]; then
        log_error "Spatial requested, but $SPATIAL_PROJ_DB was not found"
        log_error "Install spatial dependencies first or rerun without --skip-vcpkg"
        exit 1
    fi
    if [ ! -d "$SPATIAL_PROJ_DIR" ]; then
        log_error "Spatial source directory not found at $SPATIAL_PROJ_DIR"
        exit 1
    fi
    if [ ! -f "$SPATIAL_PROJ_MODULE" ]; then
        log_error "Spatial PROJ module not found at $SPATIAL_PROJ_MODULE"
        exit 1
    fi

    log_info "Patching spatial memvfs sqlite URI open flags..."
    sed -i 's/SQLITE_OPEN_READONLY, "memvfs"/SQLITE_OPEN_READONLY | SQLITE_OPEN_URI, "memvfs"/' "$SPATIAL_PROJ_MODULE"
    log_success "Spatial memvfs open flags patched"

    log_info "Regenerating spatial embedded proj_db.c from vcpkg PROJ database..."
    cp "$SPATIAL_PROJ_DB" "$SPATIAL_PROJ_DIR/proj.db"
    (cd "$SPATIAL_PROJ_DIR" && xxd -i proj.db > proj_db.c && rm -f proj.db)
    log_success "Spatial proj_db.c regenerated"
fi

# Step 8: Build
log_info "Step 8: Building DuckDB (5-10 minutes)..."
NUM_CORES=$(nproc)
log_info "Building with $NUM_CORES cores..."
START_TIME=$(date +%s)
EXTENSION_STATIC_BUILD=1 make -j"$NUM_CORES"
END_TIME=$(date +%s)
BUILD_TIME=$((END_TIME - START_TIME))
log_success "Build completed in $BUILD_TIME seconds"

# Step 9: Verify
log_info "Step 9: Verifying build..."
if [ ! -f "./duckdb" ]; then
    log_error "Binary not found at ./duckdb"
    exit 1
fi

BINARY_SIZE=$(du -h ./duckdb | cut -f1)
log_success "Binary created: $BINARY_SIZE"

log_info "Checking extensions..."
EXTENSION_COUNT=$(./duckdb -c "SELECT COUNT(*) FROM duckdb_extensions() WHERE loaded=true;" 2>/dev/null | grep -o '[0-9]\+' | tail -1)

if [ "$EXTENSION_COUNT" = "$EXPECTED_EXTENSIONS" ]; then
    log_success "All $EXPECTED_EXTENSIONS extensions loaded successfully!"
    
    echo ""
    echo -e "${GREEN}========================================${NC}"
    echo -e "${GREEN}BUILD SUCCESSFUL${NC}"
    echo -e "${GREEN}========================================${NC}"
    echo -e "Binary location: ${BLUE}$BUILD_DIR/duckdb${NC}"
    echo -e "Binary size: ${BLUE}$BINARY_SIZE${NC}"
    echo -e "Extensions: ${BLUE}$EXPECTED_EXTENSIONS statically linked${NC}"
    echo -e "Build time: ${BLUE}$BUILD_TIME seconds${NC}"
    echo ""
    echo "Extensions loaded:"
    ./duckdb -c "SELECT extension_name FROM duckdb_extensions() WHERE loaded=true ORDER BY extension_name;" 2>/dev/null | \
        awk '/│/ && !/extension_name/ && !/varchar/ {gsub(/│/,""); gsub(/^ +| +$/,""); if (length($0) > 0) print "  - " $0}'
    echo ""
else
    log_warning "Expected $EXPECTED_EXTENSIONS extensions, found $EXTENSION_COUNT"
    echo ""
    echo "Loaded extensions:"
    ./duckdb -c "SELECT extension_name, loaded FROM duckdb_extensions() WHERE installed=true ORDER BY extension_name;"
fi

echo ""
echo -e "${BLUE}To use DuckDB:${NC}"
echo -e "  cd $BUILD_DIR"
echo -e "  ./duckdb"
echo ""
